/**
 * MERA AI PRO - EKSİKSİZ BİLGİ BANKASI (500 SORU)
 */

export const KNOWLEDGE_BASE = {
    "İşlemciler (CPU)": [
        { q: "İşlemci (CPU) nedir?", a: "Bilgisayarın beynidir. Verileri işler, hesaplamalar yapar ve diğer bileşenler arasındaki veri akışını yönetir." },
        { q: "Çekirdek (Core) ve İzlek (Thread) farkı nedir?", a: "Çekirdekler fiziksel işlem birimleridir; izlekler ise her çekirdeğin aynı anda işleyebildiği sanal görev yollarıdır." },
        { q: "Nanometre (nm) değeri düştükçe ne olur?", a: "İşlemci içindeki transistörler küçülür, bu da daha az güç tüketimi, daha az ısınma ve daha yüksek performans sağlar." },
        { q: "Ghz (Saat Hızı) neyi ifade eder?", a: "İşlemcinin saniyede yapabildiği döngü sayısını gösterir. Yüksek Ghz, tek çekirdek performansını doğrudan artırır." },
        { q: "Önbellek (L1, L2, L3 Cache) nedir?", a: "İşlemcinin RAM'e gitmeden önce verilere çok hızlı ulaşmasını sağlayan dahili hafızadır. Oyunlarda L3 önbellek çok önemlidir." },
        { q: "TDP (Isıl Tasarım Gücü) nedir?", a: "İşlemcinin tam yük altında yaydığı ısı miktarını Watt cinsinden gösterir. Soğutucu seçimi buna göre yapılır." },
        { q: "Overclock (Hız Aşırtma) nedir?", a: "İşlemciyi üreticinin belirlediği standart hızın üzerine manuel olarak çıkarmaktır. Performansı artırır ama ısıyı ve riski yükseltir." },
        { q: "Darboğaz (Bottleneck) nedir?", a: "İşlemcinin gücünün ekran kartına yetmemesi sonucu ekran kartının tam kapasite çalışamaması durumudur." },
        { q: "Intel ve AMD farkı nedir?", a: "İki rakip üreticidir. Intel genellikle tek çekirdek ve stabilitede, AMD ise çoklu çekirdek ve fiyat/performans dengesinde öne çıkar." },
        { q: "Ryzen 3, 5, 7, 9 ne anlama gelir?", a: "İşlemcinin segmentini belirtir. 3 giriş, 5 orta, 7 üst, 9 ise en yüksek performans (enhuasist) seviyesidir." },
        { q: "İşlemci pinleri eğilirse ne olur?", a: "İşlemci çalışmaz veya belirli RAM slotları, PCIe hatları devre dışı kalır. Çok hassas bir şekilde düzeltilmeleri gerekir." },
        { q: "Termal macun ne işe yarar?", a: "İşlemci ve soğutucu arasındaki mikroskobik boşlukları doldurarak ısının verimli şekilde transfer edilmesini sağlar." },
        { q: "Stock Soğutucu yeterli mi?", a: "Giriş ve orta seviye işlemciler için yeterlidir ancak üst seviye işlemcilerde performans kaybını önlemek için kule tipi veya sıvı soğutma gerekir." },
        { q: "Delid işlemi nedir?", a: "İşlemcinin üzerindeki metal kapağı (IHS) açıp içindeki termal malzemeyi daha kalitelisiyle değiştirmektir. Çok risklidir." },
        { q: "İşlemci sıcaklığı boşta kaç olmalı?", a: "Ortalama 35-50 derece arası normaldir. Oda sıcaklığına ve soğutmaya göre değişebilir." },
        { q: "Oyunlarda işlemci kullanımı %100 olması iyi mi?", a: "Hayır. İşlemcinin ucu ucuna yettiğini ve her an takılmalar (stutter) yaşanabileceğini gösterir." },
        { q: "LGA ve PGA soket farkı?", a: "LGA'da pinler anakart üzerindedir (Intel), PGA'da pinler işlemci üzerindedir (Eski AMD)." },
        { q: "İşlemcide 'X' veya 'K' ibaresi nedir?", a: "Intel'de 'K' çarpan kilidi açık (OC edilebilir), AMD'de 'X' daha yüksek saat hızına sahip model demektir." },
        { q: "Dahili grafik birimi (iGPU) nedir?", a: "Ekran kartı olmadan görüntü almayı sağlayan, işlemci içine yerleştirilmiş küçük grafik işlemcisidir." },
        { q: "İşlemci ömrü ne kadardır?", a: "Doğru voltaj ve sıcaklıkta 10-15 yıl hatta daha fazla fiziksel olarak çalışabilir; genellikle teknolojik olarak eskir." },
        { q: "Sanal çekirdek (Hyper-Threading) nedir?", a: "Tek bir fiziksel çekirdeğin iki farklı işi aynı anda yürütmesini sağlayan teknolojidir." },
        { q: "İşlemci alırken mimari mi Ghz mi?", a: "Yeni mimari her zaman daha önemlidir. 5 Ghz hızındaki eski bir işlemci, 4 Ghz hızındaki yeni mimari bir işlemciden yavaş olabilir." },
        { q: "Hangi işlemci Windows 11 destekler?", a: "Genellikle Intel 8. Nesil ve AMD Ryzen 2000 serisi sonrası işlemciler resmi olarak desteklenir." },
        { q: "AVX komut seti nedir?", a: "İşlemcinin ağır matematiksel hesaplamaları ve video işleme gibi görevleri daha hızlı yapmasını sağlayan özel komutlardır." },
        { q: "İşlemci darboğazı nasıl anlaşılır?", a: "Oyun sırasında işlemci kullanımı %90-100 iken ekran kartı kullanımı %80'in altındaysa darboğaz var demektir." },
        { q: "Mobil (Laptop) ve Masaüstü işlemci farkı?", a: "Laptop işlemcileri (U, H serisi) pil ömrü için daha az güç harcar ve genellikle masaüstü versiyonlarından daha güçsüzdür." },
        { q: "İşlemci voltajı (Vcore) neden önemli?", a: "İşlemciye giden elektriktir. Fazlası yakar ve ısıtır, azı ise sistemin kilitlenmesine (BSOD) neden olur." },
        { q: "Single Core performansı neden önemli?", a: "Çoğu oyun hala ana yükü tek bir çekirdek üzerine bindirir; bu yüzden FPS için tek çekirdek gücü kritiktir." },
        { q: "IPC (Instruction Per Clock) nedir?", a: "İşlemcinin her saat döngüsünde yapabildiği iş miktarıdır. Mimari gelişimin temel göstergesidir." },
        { q: "Soğutucu montajı çok sıkılırsa ne olur?", a: "Anakart yolları zarar görebilir veya işlemci soketine aşırı baskıdan dolayı RAM kanalları çalışmayabilir." },
        { q: "İşlemci neden throttle (hız kesme) yapar?", a: "Sıcaklık güvenli sınırı (genelde 95-100 derece) geçtiğinde işlemci kendini yakmamak için hızını düşürür." },
        { q: "P-Core ve E-Core nedir?", a: "Intel'in yeni yapısı. P (Performance) ağır işler için, E (Efficiency) arka plan ve hafif işler içindir." },
        { q: "Ryzen Threadripper nedir?", a: "İş istasyonları için üretilen, çok fazla çekirdek (64-96+) barındıran devasa işlemci serisidir." },
        { q: "İşlemci fanı hangi yöne bakmalı?", a: "Havayı işlemci bloğuna üflemeli ve bu hava kasanın arkasındaki egzoz fanına doğru yönlendirilmelidir." },
        { q: "BIOS üzerinden işlemci nasıl test edilir?", a: "BIOS'ta genellikle 'Health' veya 'Monitor' kısmında sıcaklık ve voltaj değerleri görülebilir." },
        { q: "Prime95 testi nedir?", a: "İşlemciyi en ağır yük altına sokan stres testidir. Sistemin stabilitesini ölçmek için kullanılır." },
        { q: "İşlemci kutusundaki 'Tray' ne demek?", a: "Kutusuz, fansız ve sadece plastik koruma içinde satılan, genellikle daha ucuz olan sürümdür." },
        { q: "APU sistem nedir?", a: "Harici ekran kartı olmayan, oyun performansı yüksek dahili grafik birimine sahip AMD işlemcili sistemlerdir." },
        { q: "İşlemciye çok voltaj vermek ömrünü kısaltır mı?", a: "Evet, 'Electromigration' denilen olay hızlanır ve işlemci zamanla kararsızlaşır." },
        { q: "Chiplet tasarımı nedir?", a: "AMD'nin kullandığı, işlemciyi tek parça yerine küçük parçalar (die) halinde üretip birleştirme yöntemidir." },
        { q: "İşlemci soğutucusunda bakır taban neden iyidir?", a: "Bakır, ısıyı alüminyumdan çok daha hızlı iletir ve bloğa daha çabuk yayar." },
        { q: "İşlemci hızı oyunda neden dalgalanır?", a: "Güç tasarrufu modları (SpeedStep/Cool'n'Quiet) veya anlık ısınmalar hızı değiştirebilir." },
        { q: "7/24 açık kalan işlemci bozulur mu?", a: "Hayır, sıcaklıklar normalse işlemciler sürekli çalışmak üzere tasarlanmıştır (Sunucular gibi)." },
        { q: "İşlemci güncellenirken anakart değişmeli mi?", a: "Eğer yeni işlemci farklı bir soket yapısı (Örn: AM4'ten AM5'e) kullanıyorsa anakart değişmelidir." },
        { q: "İşlemci pinleri nasıl temizlenir?", a: "İzopropil alkol ve çok yumuşak bir fırça ile. Statik elektriğe dikkat edilmelidir." },
        { q: "CPU-Z programı ne işe yarar?", a: "İşlemcinin mimarisini, hızını, voltajını ve revizyonunu detaylı gösteren en popüler araçtır." },
        { q: "İşlemci kapağındaki yazılar neyi anlatır?", a: "Model numarasını, üretim yerini ve 'Batch' denilen üretim serisini gösterir." },
        { q: "Soğutucu pompası CPU_FAN soketine mi takılır?", a: "Hayır, pompa genellikle 'AIO_PUMP' soketine, fanlar ise 'CPU_FAN' soketine takılır." },
        { q: "İşlemci hızı neden Windows'ta düşük görünüyor?", a: "Güç seçenekleri 'Güç Tasarrufu' modunda kalmış olabilir." },
        { q: "Sıvı metal termal macun riskli mi?", a: "Evet, iletken olduğu için anakarta damlarsa kısa devre yaptırabilir. Sadece profesyoneller uygulamalıdır." }
    ],
    "Ekran Kartları (GPU)": [
        { q: "VRAM nedir, ne işe yarar?", a: "Ekran kartının kendi belleğidir. Yüksek çözünürlüklü dokuları ve grafik verilerini geçici olarak burada tutar." },
        { q: "Paylaşımlı ve Harici ekran kartı farkı nedir?", a: "Paylaşımlı (iGPU) işlemci içindedir ve sistem RAM'ini kullanır. Harici (dGPU) kendi belleği ve soğutması olan güçlü bir birimdir." },
        { q: "Ray Tracing (Işın İzleme) nedir?", a: "Işığın fiziksel davranışını simüle ederek oyunlarda gerçekçi yansıma, gölge ve aydınlatma sağlayan teknolojidir." },
        { q: "DLSS ve FSR farkı?", a: "DLSS NVIDIA'nın yapay zeka birimlerini kullanır; FSR ise AMD'nin her kartta çalışan yazılımsal çözümüydü (yeni sürümler hibrit)." },
        { q: "Ekran kartında 'TGP' ve 'TDP' nedir?", a: "TGP ekran kartının tamamının çektiği toplam güçtür. Güç kaynağı seçerken TGP değerine bakılır." },
        { q: "Ekran kartı sıcaklığı 85 derece normal mi?", a: "Sınır değerdir. Genellikle 70-80 arası normal kabul edilir. 85+ derece fan hızını artırmanızı veya bakımı işaret eder." },
        { q: "LHR (Low Hash Rate) ekran kartı nedir?", a: "Kripto para madenciliğini engellemek için kazım hızı yazılımsal olarak kısıtlanmış kartlardır." },
        { q: "Ekran kartında 'Coil Whine' nedir?", a: "Yüksek akım geçen bobinlerin titreşerek ince bir cızırtı sesi çıkarmasıdır. Performansa zararı yoktur ama ses yapabilir." },
        { q: "Ekran kartı driver (sürücü) neden güncellenir?", a: "Yeni çıkan oyunlarda FPS artışı, hata düzeltmeleri ve yeni özellikler (DLSS vb.) kazanmak için." },
        { q: "PCIe x16 slotu nedir?", a: "Ekran kartının anakarta takıldığı yüksek hızlı veri yoludur. Sayı hattın genişliğini gösterir." },
        { q: "Ekran kartı takarken çıt sesi gelmeli mi?", a: "Evet, slotun sonundaki plastik kilit kartı tam oturunca kapanmalı ve o ses gelmelidir." },
        { q: "GPU 'Hot Spot' sıcaklığı nedir?", a: "Çipin üzerindeki en sıcak noktadır. Normal sıcaklıktan 15-20 derece daha yüksek olması olağandır." },
        { q: "Ekran kartı neden görüntü vermez?", a: "Güç kabloları takılmamış olabilir, RAM hatası olabilir veya kart slota tam oturmamış olabilir." },
        { q: "RTX ve GTX farkı?", a: "RTX serisi donanımsal ışın izleme ve yapay zeka (Tensor) çekirdeklerine sahiptir, GTX ise daha eski/saf performans serisidir." },
        { q: "Mining yapılmış ekran kartı alınır mı?", a: "Sıcaklıkları ve fanları normalse alınabilir ancak VRAM çiplerinin çok yorulmuş olma riski vardır." },
        { q: "Ekran kartı fanları neden bazen dönmüyor?", a: "Çoğu kart 'Zero RPM' özelliğine sahiptir; 60 dereceye ulaşmadan fanları çalıştırmaz." },
        { q: "SLI ve Crossfire öldü mü?", a: "Evet, modern oyunlarda iki ekran kartını birleştirmek artık desteklenmiyor ve verimli değil." },
        { q: "Ekran kartı nasıl temizlenir?", a: "Kompresör ile tozlar alınmalı; fanlar tutularak hava verilmelidir (fanın dönmesi voltaj üretebilir)." },
        { q: "Blower fanlı ekran kartı nedir?", a: "Tek bir fanla havayı arkadan dışarı atan kartlardır; çok gürültülüdür ve sıcak çalışırlar." },
        { q: "VRAM yetmezse ne olur?", a: "Oyun ani takılmalar (stutter) yapar ve dokular geç yüklenir veya düşük çözünürlüklü görünür." },
        { q: "Ekran kartı dikey takılırsa ısınır mı?", a: "Eğer kasa camına çok yakınsa hava alamaz ve 10-15 derece daha sıcak çalışabilir." },
        { q: "GPU-Z üzerinden sahte kart nasıl anlaşılır?", a: "Programda model isminin yanında [FAKE] yazıyorsa o kart sahtedir." },
        { q: "Artifact (Görüntü Bozulması) nedir?", a: "Ekranda çıkan renkli çizgiler veya karelerdir. Genelde GPU arızası veya aşırı ısınma belirtisidir." },
        { q: "Ekran kartına Undervolt yapmak mantıklı mı?", a: "Evet, performansı düşürmeden sıcaklığı 5-10 derece düşürebilir ve elektrik tasarrufu sağlar." },
        { q: "GPU 'Sag' (Sarkma) nedir?", a: "Ağır kartların zamanla aşağı doğru bükülmesidir. Destek aparatı kullanmak slota zarar gelmesini önler." },
        { q: "MSI Afterburner ne işe yarar?", a: "Oyun içinde sıcaklık, FPS ve kullanım değerlerini izlemeye ve karta OC/UV yapmaya yarar." },
        { q: "CUDA çekirdeği nedir?", a: "NVIDIA'nın paralel hesaplama yapan birimleridir; render ve yapay zeka işlerinde çok önemlidir." },
        { q: "Ekran kartı fırınlama (Baking) nedir?", a: "Bozulan kartı fırına verip lehimleri tazelemeye çalışmaktır; geçici bir çözümdür ve çok risklidir." },
        { q: "Reference Design (Founder's Edition) nedir?", a: "Çip üreticisinin (NVIDIA/AMD) kendi ürettiği standart tasarımlı kartlardır." },
        { q: "Ekran kartı BIOS'u (VBIOS) güncellenir mi?", a: "Evet, bazen güç limitini artırmak veya hataları çözmek için üreticiler güncelleme yayınlar." },
        { q: "VRAM markası (Samsung, Micron, Hynix) önemli mi?", a: "OC potansiyeli için önemlidir; genelde Samsung bellekler en stabil olanlardır." },
        { q: "DisplayPort mu HDMI mı?", a: "Yüksek Hz ve G-Sync desteği için genellikle DisplayPort daha avantajlıdır." },
        { q: "Ekran kartı darboğazı işlemciye zarar verir mi?", a: "Hayır, sadece ekran kartının tam performansını kullanamazsınız, donanımsal bir zarar oluşmaz." },
        { q: "Low Profile ekran kartı nedir?", a: "Çok ince kasalar için üretilmiş, yüksekliği az olan özel kartlardır." },
        { q: "GPU Boost teknolojisi nedir?", a: "Kartın sıcaklığı ve gücü uygunsa saat hızını otomatik olarak en tepeye çıkarmasıdır." },
        { q: "12-pin veya 16-pin (12VHPWR) kablosu nedir?", a: "RTX 4000 serisiyle gelen, tek kablodan çok yüksek güç taşıyan yeni nesil konnektördür." },
        { q: "Ekran kartı garantisi macun değiştirince bozulur mu?", a: "Çoğu markada vidadaki güvenlik etiketi yırtılırsa garanti bozulur." },
        { q: "Düzgün takılmayan ekran kartı anakartı yakar mı?", a: "Kısa devreye neden olursa anakartın PCIe slotunu veya kartın kendisini yakabilir." },
        { q: "FPS Sabitlemek ekran kartını yorar mı?", a: "Tam tersi, kartın boş yere %100 çalışmasını engelleyerek ömrünü uzatır ve serin tutar." },
        { q: "Hangi marka ekran kartı en iyisi?", a: "ASUS, MSI ve Gigabyte ana markalardır. Her markanın giriş (Ventus/Dual) ve üst (Strix/Suprim) modelleri vardır." },
        { q: "G-Sync Compatible ne demek?", a: "FreeSync bir monitörün NVIDIA kartlarla sorunsuz çalıştığının onaylanmış halidir." },
        { q: "Ekran kartı kutusunda neden statik poşet var?", a: "Kartı statik elektrik çarpmasından ve nemden korumak için." },
        { q: "GPU mimarisi (Ada Lovelace, RDNA 3) nedir?", a: "Kartın tasarım teknolojisidir. Mimari değiştikçe performans verimliliği devasa artar." },
        { q: "Ekran kartı olmadan PC çalışır mı?", a: "İşlemcinizde dahili grafik (iGPU) varsa çalışır, yoksa görüntü alamazsınız." },
        { q: "Re-Size BAR desteği nedir?", a: "İşlemcinin tüm GPU belleğine tek seferde erişmesini sağlayıp FPS'i artıran teknolojidir." },
        { q: "Ekran kartı fan hızı kaç olmalı?", a: "Otomatikte bırakmak en iyisidir; 80 dereceyi geçiyorsa manuel olarak %70-80'e çekilebilir." },
        { q: "GPU çekirdek hızı mı bellek hızı mı?", a: "Her ikisi de önemlidir ancak çekirdek hızı FPS'e daha doğrudan etki eder." },
        { q: "LHR kilidi tamamen kırıldı mı?", a: "Evet, yazılımlar artık madencilikte tam performansa ulaşabiliyor." },
        { q: "Harici ekran kartı kutusu (eGPU) nedir?", a: "Laptoplara Thunderbolt üzerinden masaüstü ekran kartı bağlamayı sağlayan kutulardır." },
        { q: "Ekran kartı alırken Bit değeri (128, 256) önemli mi?", a: "Eskisi kadar değil; yeni mimarilerde önbellek (cache) büyük olduğu için düşük bitlerde de yüksek performans alınabiliyor." }
    ],
    "RAM (Bellek)": [
        { q: "RAM nedir, ne işe yarar?", a: "Bilgisayarın kısa süreli hafızasıdır. İşlemcinin o an ihtiyaç duyduğu verileri çok hızlı bir şekilde depolar." },
        { q: "Dual Channel (Çift Kanal) nedir?", a: "İki adet RAM çubuğunun aynı anda kullanılarak veri yolunun 128-bit'e çıkarılmasıdır. Performansı ciddi oranda artırır." },
        { q: "RAM frekansı (Mhz) hızı etkiler mi?", a: "Evet, özellikle AMD Ryzen işlemcilerde yüksek Mhz doğrudan işlemci performansını ve FPS'i artırır." },
        { q: "CL (Gecikme Değeri) nedir?", a: "RAM'in bir komuta ne kadar sürede yanıt verdiğidir. Bu değer ne kadar düşükse RAM o kadar hızlı tepki verir." },
        { q: "DDR4 ve DDR5 farkı nedir?", a: "DDR5 daha yüksek bant genişliği, daha düşük voltaj ve daha yüksek frekanslar sunar; soketleri birbirinden farklıdır." },
        { q: "8GB RAM günümüzde yeterli mi?", a: "Ofis işleri için yeterlidir ancak modern oyunlar ve çoklu görevler için artık standart 16GB'dır." },
        { q: "Farklı marka RAM'ler beraber çalışır mı?", a: "Çalışabilir ancak Mhz ve CL değerleri farklıysa sistem en yavaş olan RAM'e göre hızını sabitler; uyumsuzluk riski vardır." },
        { q: "XMP (Extreme Memory Profile) nedir?", a: "RAM'in üretildiği yüksek hızda çalışması için BIOS'tan açılması gereken hazır hız profilidir." },
        { q: "RAM slotları neden 2 ve 4 olarak takılır?", a: "Anakartlarda Dual Channel özelliğini aktif etmek için genellikle 2. ve 4. slotların (işlemciden uzağa doğru) kullanılması gerekir." },
        { q: "RGB RAM performansı etkiler mi?", a: "Hayır, sadece görseldir. Çok küçük bir miktar ek güç harcar." },
        { q: "RAM 'Memtest86' testi nedir?", a: "RAM'de donanımsal bir arıza veya hata olup olmadığını anlamak için yapılan en kapsamlı testtir." },
        { q: "Sanal Bellek (Pagefile) nedir?", a: "RAM dolduğunda Windows'un SSD veya HDD'nin bir kısmını RAM gibi kullanmasıdır; çok yavaştır." },
        { q: "RAM kapasitesi FPS'i artırır mı?", a: "Eğer RAM miktarınız ucu ucuna yetiyorsa artırır, ancak zaten 32GB RAM'iniz varsa 64GB yapmak FPS'i artırmaz." },
        { q: "SoG (Single Sided) ve DoG (Double Sided) RAM nedir?", a: "RAM üzerindeki bellek çiplerinin tek yüzde mi çift yüzde mi olduğunu belirtir." },
        { q: "RAM neden 'Donanıma Ayrılmış' görünür?", a: "Dahili ekran kartı (iGPU) RAM'in bir kısmını kendine ayırmış olabilir veya RAM tam oturmamış olabilir." },
        { q: "ECC RAM nedir?", a: "Hata düzeltme koduna sahip RAM'dir. Genellikle sunucularda ve iş istasyonlarında veri güvenliği için kullanılır." },
        { q: "RAM voltajı kaç olmalı?", a: "DDR4 için standart 1.2V, XMP ile 1.35V'tur. DDR5'te ise 1.1V standarttır." },
        { q: "Laptop RAM'i masaüstüne takılır mı?", a: "Hayır, laptoplar 'SO-DIMM' denilen daha kısa boyutlu RAM'ler kullanır." },
        { q: "RAM neden ısınır?", a: "Çok yüksek voltaj verildiğinde veya kasa içi hava akışı kötüyse ısınabilir; genellikle soğutucu bloğu (Heatsink) yeterlidir." },
        { q: "3200Mhz RAM neden 2133Mhz görünüyor?", a: "BIOS'tan XMP veya DOCP profili açılmadığı için RAM temel hızında çalışıyordur." },
        { q: "RAM'in sahte olduğu nasıl anlaşılır?", a: "Thaiphoon Burner programı ile bellek çiplerinin seri numarasına ve üreticisine bakılabilir." },
        { q: "ReadyBoost nedir?", a: "Eski bir Windows özelliğidir, USB belleği RAM gibi kullanmaya çalışır; SSD'li sistemlerde işe yaramaz." },
        { q: "RAM üzerinde neden statik koruma var?", a: "RAM çiplerinin statik elektrikten anında bozulma riski çok yüksektir." },
        { q: "Dört kanal (Quad Channel) nedir?", a: "Üst seviye iş istasyonu anakartlarında 4 veya 8 RAM slotunun aynı anda yüksek bant genişliğiyle çalışmasıdır." },
        { q: "RAM gecikmesi (Latency) nasıl hesaplanır?", a: "Genellikle (CL * 2000) / Mhz formülüyle nanosaniye cinsinden gerçek gecikme bulunur." },
        { q: "High Profile ve Low Profile RAM nedir?", a: "RAM'in üzerindeki soğutucunun yüksekliğidir; kule tipi soğutucular bazen yüksek RAM'lere çarpar." },
        { q: "RAM 'Stutter' (takılma) yapar mı?", a: "Evet, RAM yetersizse veya hatalı çalışıyorsa oyunlarda anlık donmalar yaşanır." },
        { q: "DDR3 anakarta DDR4 RAM takılır mı?", a: "Hayır, her DDR neslinin çentik yeri farklıdır, fiziksel olarak uymaz." },
        { q: "Anakartın desteklediği maksimum RAM hızı nedir?", a: "Anakart üreticisinin web sitesindeki özellikler kısmında 'OC' ibaresiyle belirtilen değerdir." },
        { q: "RAM'leri temizlemek için silgi kullanılır mı?", a: "Evet, RAM'in sarı uçlarını (pinlerini) yumuşak bir silgiyle nazikçe temizlemek oksitlenmeyi giderir." },
        { q: "RAM SPD verisi nedir?", a: "RAM'in içinde kayıtlı olan hız, voltaj ve zamanlama bilgilerinin olduğu küçük bir dosyadır." },
        { q: "32GB RAM tek modül mü çift modül mü?", a: "Her zaman çift modül (2x16GB) daha iyidir çünkü Dual Channel performansı sağlar." },
        { q: "DDR5'teki 'On-die ECC' nedir?", a: "DDR5 RAM'lerin kendi içinde hata düzeltme yapmasıdır; bu onu standart ECC RAM ile aynı yapmaz." },
        { q: "RAM neden 'Mavi Ekran' verir?", a: "Uyumsuz frekans, arızalı çip veya yetersiz voltaj en büyük nedenlerdir." },
        { q: "RAM'in MHz değerini çok artırmak neyi yakar?", a: "Genellikle RAM bozulmaz ama işlemci içindeki bellek kontrolcüsü (IMC) zarar görebilir." },
        { q: "V-Color, TeamGroup, G.Skill güvenilir mi?", a: "Evet, bunlar bilinen kaliteli RAM markalarıdır; önemli olan içindeki çip üreticisidir (Samsung/SK Hynix/Micron)." },
        { q: "RAM frekansını Windows'tan görebilir miyim?", a: "Evet, Görev Yöneticisi -> Performans -> Bellek kısmında 'Hız' olarak yazar." },
        { q: "RAM'lerde 'Single Rank' ve 'Dual Rank' farkı?", a: "Verinin bellek yongalarına nasıl dağıtıldığıdır; Dual Rank genellikle biraz daha performanslıdır." },
        { q: "XMP açınca PC açılmıyor?", a: "İşlemciniz veya anakartınız o yüksek hızı desteklemiyor olabilir; voltajı manuel artırmak gerekebilir." },
        { q: "RAM'lerin üzerindeki etiketi sökmek garantiyi bozar mı?", a: "Evet, seri numarasının olduğu etiket sökülürse çoğu marka garanti dışı bırakır." },
        { q: "Bellek kontrolcüsü (IMC) nedir?", a: "İşlemcinin içinde RAM ile iletişimi sağlayan birimdir. RAM hızı buna bağlıdır." },
        { q: "1.5V DDR4 RAM için güvenli mi?", a: "Günlük kullanım için çok yüksektir; genellikle 1.4V üstü özel soğutma gerektirir." },
        { q: "Hangi oyunlar 32GB RAM ister?", a: "Star Citizen, Microsoft Flight Simulator ve ağır modlu şehir kurma oyunları 32GB RAM'den faydalanır." },
        { q: "RAM slotu bozulursa ne olur?", a: "O slota takılan RAM algılanmaz veya sistem sürekli reset atar." },
        { q: "BIOS güncellemesi RAM uyumluluğunu artırır mı?", a: "Kesinlikle! Birçok BIOS güncellemesi 'Memory Compatibility' iyileştirmesi içerir." },
        { q: "RAM'lerdeki soğutma blokları gerçekten soğutuyor mu?", a: "DDR4'te çok fark etmez ama voltajı yüksek DDR5'lerde ısınmayı engellemek için önemlidir." },
        { q: "DDR5'te PMIC nedir?", a: "Güç yönetim devresidir. Artık anakart yerine doğrudan RAM'in üzerinde bulunur." },
        { q: "Gear 1 ve Gear 2 modu nedir?", a: "İşlemci hızı ile RAM hızının birebir (1:1) veya yarı yarıya (1:2) çalışmasıdır; Gear 1 daha hızlıdır." },
        { q: "RAM 'CAS Latency' mi MHz mi?", a: "İdeal olan yüksek MHz ve düşük CL dengesidir. Ancak günümüzde yüksek MHz (bant genişliği) daha önceliklidir." },
        { q: "Mera AI RAM önerisi yapar mı?", a: "Evet, sistemine ve bütçene en uygun frekans ve kapasiteyi sana söyleyebilirim." }
    ],
    "Anakart": [
        { q: "Anakart nedir, ne işe yarar?", a: "Anakart, bilgisayarın tüm iç ve dış bileşenlerinin üzerine takıldığı ve bu bileşenler arasındaki veri iletişimini koordine eden temel devredir." },
        { q: "ATX, Micro-ATX ve Mini-ITX farkı nedir?", a: "Bunlar anakart boyutlarıdır. ATX standart büyük boy, Micro-ATX orta boy, Mini-ITX ise çok küçük kasalar için tasarlanmış en küçük boydur." },
        { q: "Anakart seçerken en önemli şey nedir?", a: "İlk öncelik işlemci uyumluluğu (Soket tipi) ve ardından kasanıza sığacak boyut (Form faktörü) olmalıdır." },
        { q: "Anakart performansı (FPS) etkiler mi?", a: "Anakart doğrudan FPS artırmaz ancak stabiliteyi etkiler. Zayıf bir anakart, güçlü bir işlemcinin ısınmasına ve hız düşürmesine neden olarak FPS'i dolaylı düşürebilir." },
        { q: "Chipset (Yonga Seti) nedir?", a: "Anakartın beynidir. Hangi işlemcileri desteklediğini, kaç tane USB veya SATA portu olacağını ve overclock desteğini belirler." },
        { q: "Intel B, H ve Z serisi farkları?", a: "H giriş seviyesi (temel kullanım), B orta segment (fiyat/performans), Z ise üst segmenttir (overclock ve en yüksek özellikler)." },
        { q: "AMD A, B ve X serisi farkları?", a: "A giriş seviyesi, B orta segment (overclock destekli), X ise en yüksek performans ve en çok genişleme yuvası sunan seridir." },
        { q: "LGA 1700 soketi nedir?", a: "Intel'in 12, 13 ve 14. nesil işlemcileri için kullandığı fiziksel bağlantı yapısıdır." },
        { q: "AM4 ve AM5 soketi farkı?", a: "AM4, AMD'nin Ryzen 5000 serisine kadar olan eski yapısıdır. AM5 ise DDR5 destekli, yeni nesil Ryzen 7000+ işlemciler için kullanılan sokettir." },
        { q: "Soket uyumsuzsa ne olur?", a: "İşlemci anakarta fiziksel olarak oturmaz ve zorlanırsa hem işlemci hem anakart pinleri kalıcı olarak zarar görür." },
        { q: "VRM (Voltaj Düzenleyici Modül) nedir?", a: "Güç kaynağından gelen elektriği işlemcinin kullanabileceği düşük ve stabil voltaja çeviren parçalardır. Kalitesi, sistem kararlılığı için kritiktir." },
        { q: "Anakartta VRM soğutması neden önemli?", a: "Güçlü işlemciler çok akım çeker, bu da VRM'lerin ısınmasına yol açar. İyi soğutulmayan VRM'ler işlemcinin performansını kısıtlar." },
        { q: "PCIe 4.0 ve PCIe 5.0 farkı nedir?", a: "PCIe 5.0, PCIe 4.0'ın sunduğu bant genişliğini ikiye katlar. Bu, özellikle yeni nesil aşırı hızlı SSD'ler için önemlidir." },
        { q: "M.2 slotu nedir?", a: "NVMe SSD'lerin takıldığı, doğrudan anakart veri yoluna bağlı olan çok yüksek hızlı depolama yuvasıdır." },
        { q: "SATA portları hala gerekli mi?", a: "Eski tip HDD veya 2.5 inç SSD takmak için gereklidir, ancak yeni sistemlerde yerini yavaş yavaş M.2 slotlarına bırakmaktadır." },
        { q: "BIOS (UEFI) nedir?", a: "Anakartın donanımı başlatmasını sağlayan düşük seviyeli yazılımdır. Ayarlar (Fan hızı, OC, Boot) buradan yapılır." },
        { q: "BIOS güncellemesi neden yapılır?", a: "Yeni çıkan işlemcilere destek sağlamak, sistem stabilitesini artırmak ve güvenlik açıklarını kapatmak için yapılır." },
        { q: "BIOS güncellemesi sırasında elektrik kesilirse ne olur?", a: "Anakart 'brick' olabilir (çalışmaz hale gelir). Bu durumda teknik servis veya BIOS Flashback özelliği gerekebilir." },
        { q: "BIOS Flashback özelliği nedir?", a: "İşlemci veya RAM takılı olmasa bile, sadece bir USB bellek ile anakartın BIOS'unu güncellemenizi sağlayan hayat kurtarıcı bir özelliktir." },
        { q: "Dual BIOS nedir?", a: "Anakartta iki adet BIOS çipi bulunmasıdır. Birincisi bozulursa, ikincisi otomatik devreye girerek sistemi kurtarır." },
        { q: "Wi-Fi destekli anakart almaya değer mi?", a: "Kablolu internet çekemiyorsanız değer. Bu anakartlar dahili Wi-Fi ve Bluetooth ile gelir, ekstra adaptör gerektirmez." },
        { q: "I/O Shield (Ayna) nedir?", a: "Anakart portlarının kasanın arkasında düzgün görünmesini sağlayan ve statik elektriği engelleyen metal plakadır." },
        { q: "USB 3.2 Gen 2x2 nedir?", a: "20 Gbps hıza ulaşabilen, en hızlı USB bağlantı standartlarından biridir." },
        { q: "Thunderbolt 4 anakartta ne işe yarar?", a: "Çok yüksek hızlı veri aktarımı, görüntü çıkışı ve güç iletimi sağlayan profesyonel bir bağlantı teknolojisidir." },
        { q: "RGB ve ARGB header farkı?", a: "RGB 12V olup tüm ledleri aynı renk yakar. ARGB 5V olup her ledi farklı renk yakarak animasyon yapmanıza olanak sağlar." },
        { q: "Anakarttaki EZ Debug LED'ler nedir?", a: "CPU, RAM, GPU veya Boot sırasında bir hata olduğunda yanan küçük ışıklardır. Sorunun nerede olduğunu anlamanızı sağlar." },
        { q: "Clear CMOS (BIOS Sıfırlama) nasıl yapılır?", a: "Anakart üzerindeki pili çıkarıp 30 saniye bekleyerek veya 'Clear CMOS' pinlerine kısa devre yaptırarak BIOS ayarları fabrika ayarlarına döndürülür." },
        { q: "Anakart pili (CR2032) biterse ne olur?", a: "Bilgisayar saati sürekli sıfırlanır ve BIOS ayarlarınız her açılışta kaybolur." },
        { q: "Anakartta statik elektrik nasıl boşaltılır?", a: "Güç kablosunu çekin ve kasanın açma tuşuna 10-15 saniye basılı tutun." },
        { q: "Bilgisayar tetik almıyor, anakart bozuk mu?", a: "Önce PSU ve kasanın açma düğmesi kabloları kontrol edilmelidir. Anakartın üzerinde ışık yanmıyorsa arızalı olabilir." },
        { q: "VRM Faz sayısı (Power Phases) nedir?", a: "Güç kaynağındaki enerjinin kaç kanaldan işlemciye dağıtıldığını gösterir. Faz sayısı arttıkça voltaj daha stabil ve serin iletilir." },
        { q: "Anakartta 'Standoff' (Yükseltme Vidası) neden önemlidir?", a: "Anakartın kasanın metaline değip kısa devre yapmasını önler. Takılmazsa anakart anında yanabilir." },
        { q: "Dahili Ses Kartı (Audio Codec) önemli mi?", a: "Evet, özellikle üst seviye anakartlardaki ALC1220 gibi çipler, stüdyo kalitesine yakın ses deneyimi sunar." },
        { q: "Anakartta RAM slotu neden 4 tane?", a: "Daler fazla RAM kapasitesi ve esneklik sağlamak için. Genellikle ana akım işlemciler yine de çift kanal (Dual Channel) çalışır." },
        { q: "Heatsink (Soğutma Bloğu) nerelerde bulunur?", a: "VRM'lerin, Chipset'in ve bazen M.2 SSD slotlarının üzerinde bulunur." },
        { q: "POST (Power-On Self Test) nedir?", a: "Bilgisayar açılırken anakartın tüm donanımları test ettiği kısa süreli kontroldür." },
        { q: "Anakartın kaç katmanlı (PCB Layer) olması önemli mi?", a: "Evet, katman sayısı arttıkça sinyal kalitesi artar ve ısı dağılımı iyileşir (Örn: 6-layer, 8-layer)." },
        { q: "TPM 2.0 nedir?", a: "Donanım tabanlı güvenlik çipidir. Windows 11 kurulumu için zorunludur." },
        { q: "XMP/EXPO desteği anakarta mı bağlıdır?", a: "Hem anakarta hem işlemciye bağlıdır. Anakartın BIOS'u bu yüksek hız profillerini desteklemelidir." },
        { q: "Fan Header sayıları neden farklı?", a: "Daha fazla kasa fanı takabilmek için anakart üzerindeki fan girişlerinin sayısı modelden modele değişir." },
        { q: "Anakart kutusundan neler çıkmalı?", a: "Anakart, arka ayna (varsa), SATA kabloları, M.2 vidaları ve Wi-Fi antenleri (varsa)." },
        { q: "PCIe Kilidi neden var?", a: "Ağır ekran kartlarının yerinden çıkmasını veya slota zarar vermesini önlemek için bir güvenlik tırnağıdır." },
        { q: "Anakart üzerindeki 'Buzzer' ne işe yarar?", a: "Sistemdeki hataları bip sesleri (Error Beeps) ile kullanıcıya bildiren küçük bir hoparlördür." },
        { q: "OC (Overclock) anakarta zarar verir mi?", a: "Bilinçsiz voltaj artışı anakart VRM'lerini yakabilir veya ömrünü kısaltabilir." },
        { q: "Yüksek MHz RAM her anakartta çalışır mı?", a: "Hayır, anakartın üretici sayfasındaki QVL (Desteklenen RAM'ler) listesine bakılmalıdır." },
        { q: "Anakart temizliği nasıl yapılır?", a: "Sıkıştırılmış hava (kompresör) ile tozları temizlenebilir. Sıvı teması asla olmamalıdır." },
        { q: "Güç girişi (24-pin ve 8-pin) neden ayrı?", a: "24-pin anakartın genel gücü, 8-pin ise işlemcinin özel güç ihtiyacı içindir." },
        { q: "Anakartta 'Daisy Chain' bellek yapısı nedir?", a: "RAM slotlarının işlemciye olan uzaklığıyla ilgili bir tasarım yoludur, bellek hızını etkiler." },
        { q: "OEM anakart nedir?", a: "Hazır sistem üreticileri (HP, Dell vb.) için üretilen, perakende satılmayan ve özellikleri kısıtlı anakartlardır." },
        { q: "Anakartı ne zaman yükseltmeliyim?", a: "İşlemci nesli değiştiğinde veya yeni bir depolama/ekran kartı teknolojisine (PCIe 5.0 gibi) geçmek istediğinizde." }
    ],
    "Depolama (SSD / HDD / NVMe)": [
        { q: "SSD ve HDD arasındaki en temel fark nedir?", a: "HDD'ler veriyi dönen manyetik diskler üzerine yazar (mekanik); SSD'ler ise veriyi çip üzerindeki hücrelere kaydeder (elektronik). SSD'ler çok daha hızlı, sessiz ve dayanıklıdır." },
        { q: "SATA SSD ve NVMe M.2 SSD farkı nedir?", a: "SATA SSD'ler kablo veya slot üzerinden max 550 MB/s hız sunarken, NVMe SSD'ler doğrudan PCIe hattını kullanarak 3500 ile 14000 MB/s arası hızlara ulaşabilir." },
        { q: "HDD hala satın alınmalı mı?", a: "Sadece yüksek kapasiteli veri arşivleme (video, fotoğraf yedekleme) için mantıklıdır. Windows işletim sistemi ve oyunlar için HDD artık önerilmez." },
        { q: "SSD takmak eski bilgisayarı hızlandırır mı?", a: "Kesinlikle! Eski bir sisteme yapılabilecek en etkili yükseltme HDD yerine SSD takmaktır. Açılış ve uygulama hızları 10 kata kadar artabilir." },
        { q: "M.2 her zaman NVMe mi demektir?", a: "Hayır. M.2 bir slot tipidir. Bu slotun içine hem yavaş olan 'SATA M.2' hem de hızlı olan 'NVMe M.2' takılabilir. Alırken protokolüne bakılmalıdır." },
        { q: "Okuma ve Yazma hızı neyi ifade eder?", a: "Okuma hızı bir dosyanın ne kadar hızlı açıldığını (oyun yükleme ekranı gibi), Yazma hızı ise bir dosyanın diske ne kadar hızlı kaydedildiğini belirler." },
        { q: "Gen 3, Gen 4 ve Gen 5 SSD farkları?", a: "Gen 3 (3500 MB/s), Gen 4 (7500 MB/s) ve Gen 5 (14000 MB/s) civarı maksimum hızlar sunar. Her nesil hızı yaklaşık ikiye katlar." },
        { q: "IOPS nedir?", a: "Saniyedeki giriş/çıkış işlem sayısıdır. Rastgele okuma hızı için kritiktir; Windows'un ne kadar 'akıcı' tepki vereceğini IOPS değeri belirler." },
        { q: "DRAM Cache barındıran SSD neden daha iyidir?", a: "DRAM, SSD'nin üzerinde bulunan küçük bir bellek yongasıdır. Verilerin nerede olduğunu haritalandırarak diskin çok daha hızlı ve uzun ömürlü çalışmasını sağlar." },
        { q: "SSD doldukça yavaşlar mı?", a: "Evet. SSD'lerin performansı genellikle %90 doluluk oranından sonra düşmeye başlar. Yazma işlemleri için boş alan bırakmak performansı korur." },
        { q: "SLC, MLC, TLC ve QLC NAND nedir?", a: "Hücre başına düşen bit sayısıdır. SLC en kaliteli ve pahalı olandır. TLC günümüzün standart dengeli tipidir. QLC ise ucuz ama ömrü ve hızı biraz daha düşüktür." },
        { q: "3D NAND teknolojisi nedir?", a: "Hücrelerin yatay yerine dikey olarak (kat kat) dizilmesidir. Bu sayede aynı alana çok daha yüksek kapasite sığdırılabilir." },
        { q: "TBW (Total Bytes Written) nedir?", a: "SSD'nin ömrü boyunca üzerine yazılabilecek toplam veri miktarını ifade eder. Bu değer ne kadar yüksekse SSD o kadar dayanıklıdır." },
        { q: "SSD'lerde TRIM komutu ne işe yarar?", a: "İşletim sisteminin SSD'ye hangi veri bloklarının artık kullanılmadığını bildirmesidir. Performansın zamanla düşmesini engeller." },
        { q: "MTBF nedir?", a: "Hatalar arası ortalama süre demektir. Diskin donanımsal arıza yapmadan önce ne kadar süre (genelde milyon saat) çalışmasının beklendiğini gösterir." },
        { q: "DirectStorage teknolojisi nedir?", a: "Oyun verilerinin işlemciye uğramadan doğrudan SSD'den ekran kartına aktarılmasıdır. Bu, yükleme sürelerini neredeyse sıfıra indirir." },
        { q: "Oyunları harici SSD'den oynamak mantıklı mı?", a: "USB 3.1 veya üzeri bir bağlantı varsa dahili diske yakın performans alabilirsiniz. Ancak USB 2.0 çok yavaş kalacaktır." },
        { q: "SSD sıcaklığı ne kadar olmalı?", a: "Normal çalışma sıcaklığı 30-50 derecedir. NVMe SSD'ler 70 dereceyi geçerse performans düşürür (Throttling)." },
        { q: "SSD soğutucusu (Heatsink) gerekli mi?", a: "Özellikle Gen 4 ve Gen 5 NVMe SSD'ler çok ısındığı için üzerlerinde bir soğutma bloğu olması performans sürekliliği için şarttır." },
        { q: "SSD sağlığı nasıl kontrol edilir?", a: "CrystalDiskInfo veya SSD üreticisinin kendi yazılımı (Samsung Magician, WD Dashboard vb.) ile sağlık yüzdesi ve yazılan toplam veri görülebilir." },
        { q: "SSD'ye defrag (disk birleştirme) yapılır mı?", a: "Kesinlikle HAYIR! SSD'lerde hareketli parça olmadığı için birleştirme gereksizdir ve hücrelerin yazma ömrünü boş yere tüketir." },
        { q: "SSD 'Raw' formatına dönüştü, ne yapmalıyım?", a: "Dosya sistemi bozulmuş demektir. Veri kurtarma yazılımları denenebilir veya disk yeniden biçimlendirilmelidir." },
        { q: "M.2 SSD anakartta görünmüyor?", a: "M.2 slotunun BIOS'ta aktif olduğundan, SSD'nin tam oturduğundan veya slotun SATA/NVMe desteğinin doğruluğundan emin olunmalıdır." },
        { q: "SSD sağlığı neden hızlı düşer?", a: "Çok sık büyük boyutlu dosya indirme/silme yapılması veya Windows'un 'Hızlı Başlat' gibi bazı özelliklerinin diski sürekli kullanması neden olabilir." },
        { q: "Firmware güncellemesi SSD için önemli mi?", a: "Evet, üreticiler bazen veri kaybını önleyen veya performansı artıran kritik yazılım güncellemeleri yayınlar." },
        { q: "SSD over-provisioning nedir?", a: "SSD'nin bir kısmını (genelde %7-10) kullanıcıya kapatıp, o alanı disk yönetimi ve ömür uzatma için yedek olarak kullanmasıdır." },
        { q: "HDD'de 5400 RPM ve 7200 RPM farkı?", a: "RPM diskin dakikadaki dönüş hızıdır. 7200 RPM daha hızlı veri erişimi sunar ancak daha çok gürültü ve ısı üretir." },
        { q: "SSHD (Hybrid Drive) nedir?", a: "İçinde küçük bir SSD bölümü ve büyük bir HDD barındıran disklerdir. Günümüzde yerini tamamen saf SSD'lere bırakmıştır." },
        { q: "NAS diski ve standart disk farkı nedir?", a: "NAS diskleri (Örn: WD Red) 7/24 çalışmak üzere tasarlanmıştır ve titreşime karşı daha dayanıklıdır." },
        { q: "SMR ve CMR HDD farkı?", a: "CMR verileri yan yana yazar, daha performanslıdır. SMR verileri üst üste bindirerek yazar, daha yavaştır ama daha yüksek kapasite sunar." },
        { q: "SSD verileri silindiğinde geri getirmek neden zordur?", a: "TRIM özelliği nedeniyle silinen hücreler anında temizlenir. HDD'de ise üzerine veri yazılana kadar geri getirmek mümkündür." },
        { q: "2.5 inç ve 3.5 inç disk boyutları?", a: "2.5 inç genelde laptop ve SSD boyutudur. 3.5 inç ise masaüstü bilgisayarların standart HDD boyutudur." },
        { q: "M.2 SSD vidası kaybolursa ne olur?", a: "SSD yuvasından fırlayabilir ve temassızlık yapabilir. Standart bir M2 vidası ile mutlaka sabitlenmelidir." },
        { q: "SSD klonlama nedir?", a: "Eski diskteki Windows'u ve tüm verileri ayarları bozmadan yeni bir SSD'ye birebir kopyalama işlemidir." },
        { q: "SATA 3 ve SATA 2 uyumluluğu?", a: "SATA 3 bir diski SATA 2 portuna takabilirsiniz ama hızı 300 MB/s ile sınırlanır." },
        { q: "NVMe SSD'yi PCIe slotuna takabilir miyim?", a: "Evet, bir M.2 to PCIe adaptörü kullanarak ekran kartı slotuna bile SSD takabilirsiniz." },
        { q: "SSD'de 'Secure Erase' nedir?", a: "Diskteki tüm hücreleri fabrikadan çıktığı ilk günkü temiz haline getiren profesyonel silme yöntemidir." },
        { q: "Hangi SSD markaları güvenilir?", a: "Kendi NAND çiplerini üreten Samsung, Crucial (Micron), WD (Sandisk) ve SK Hynix gibi markalar genellikle en güvenilir olanlardır." },
        { q: "Chia mining SSD'yi bozar mı?", a: "Evet, Chia gibi depolama tabanlı mining işlemleri SSD'nin yazma ömrünü (TBW) çok kısa sürede bitirebilir." },
        { q: "BitLocker SSD performansını düşürür mü?", a: "Şifreleme işlemi işlemci üzerinden yapıldığı için SSD hızında fark edilmeyecek kadar küçük (%1-3) bir düşüş yaratabilir." },
        { q: "SSD'nin fiziksel ömrü mü yoksa yazma ömrü mü önce dolar?", a: "Normal bir kullanıcı için her zaman teknolojik ömür önce dolar; fiziksel ömrü bitirmek yıllar sürer." },
        { q: "U.2 SSD nedir?", a: "Genellikle sunucularda kullanılan, yüksek kapasiteli ve NVMe hızında olan farklı bir bağlantı tipidir." },
        { q: "Disklerde GPT ve MBR farkı?", a: "GPT modern sistemler için standarttır ve 2TB üzerindeki diskleri destekler. UEFI kurulum için GPT şarttır." },
        { q: "HDD sesi (tıkırtı) neyin işaretidir?", a: "Diskin okuma kafasının bozulduğunun veya fiziksel bir hasarın işaretidir. Veriler acilen yedeklenmelidir." },
        { q: "M.2 Key tipleri (B-Key, M-Key) nedir?", a: "Slotun fiziksel yapısıdır. NVMe SSD'ler genelde 'M-Key' kullanırken, SATA M.2'ler 'B+M Key' kullanır." },
        { q: "SSD alırken garanti süresi ne kadar olmalı?", a: "Kaliteli markalar genelde 5 yıl veya belirli bir TBW ömrü kadar garanti sunar." },
        { q: "Windows 11 için SSD şart mı?", a: "Zorunlu değildir ama HDD üzerinde Windows 11 kullanmak sistemin çok yavaş ve hantal çalışmasına neden olur." },
        { q: "Portable (Taşınabilir) SSD neden harici HDD'den iyidir?", a: "Daha küçük, daha hızlı ve sarsıntılara karşı çok daha dayanıklıdır (Düşürdüğünüzde veri kaybı riski çok azdır)." },
        { q: "Disk neden olması gerekenden küçük görünür?", a: "Üreticiler 1GB'ı 1000MB sayarken Windows 1024MB sayar. Ayrıca sistem dosyaları ve biçimlendirme payı alanı azaltır." },
        { q: "SSD kontrolcüsü neden önemlidir?", a: "Diskin beynidir; verilerin yazılma sırasını, hata düzeltmeyi ve diskin genel hızını belirleyen en kritik bileşendir." }
    ],
    "Güç Kaynağı (PSU)": [
        { q: "PSU nedir, ne işe yarar?", a: "PSU (Power Supply Unit), prizden gelen yüksek voltajlı AC akımı, bilgisayar parçalarının kullanabileceği düşük voltajlı DC akıma çeviren ünitedir." },
        { q: "Watt değeri neyi ifade eder?", a: "PSU'nun sisteme sağlayabileceği maksimum toplam gücü gösterir. Sisteminizin toplam tüketiminden daha yüksek bir Watt değeri seçilmelidir." },
        { q: "80 Plus sertifikası nedir?", a: "PSU'nun elektriği ne kadar verimli kullandığını gösterir. %80 ve üzeri verimlilik sunan cihazlara verilir." },
        { q: "80 Plus White, Bronze, Silver, Gold, Platinum, Titanium farkı?", a: "Bu sıralama verimlilik oranını artırır. Gold ve üzeri sertifikalar daha az ısı üretir, daha az elektrik harcar ve genellikle daha kaliteli bileşenlere sahiptir." },
        { q: "Kalitesiz PSU sisteme zarar verir mi?", a: "Evet. Dengesiz voltaj vererek parçaların ömrünü kısaltabilir veya bir kısa devre durumunda koruma devreleri olmadığı için tüm sistemi yakabilir." },
        { q: "Modüler, Yarı Modüler ve Non-Modüler PSU farkı?", a: "Non-modülerde tüm kablolar sabittir. Yarı modülerde ana kablolar sabit, diğerleri takılıp çıkarılabilir. Tam modülerde ise tüm kablolar sökülebilir, bu da kasa içi düzeni kolaylaştırır." },
        { q: "12VHPWR kablosu nedir?", a: "NVIDIA RTX 4000 serisi ekran kartları için tasarlanan, tek kablodan 600W'a kadar güç verebilen yeni nesil yüksek performans kablosudur." },
        { q: "ATX 3.0 ve ATX 3.1 standartları nedir?", a: "Yeni nesil ekran kartlarının ani güç sıçramalarını (Power Spikes) karşılamak üzere tasarlanmış, daha dayanıklı ve güncel bağlantı standartlarıdır." },
        { q: "PSU kabloları başka marka ile değiştirilir mi?", a: "HAYIR! Tam modüler olsa bile kablo pin dizilimleri markadan markaya değişir. Yanlış kablo kullanımı sistemi anında yakabilir." },
        { q: "24-pin ve 4+4 pin kabloları ne içindir?", a: "24-pin anakartın genel gücü, 4+4 (veya 8) pin ise işlemcinin özel güç beslemesi içindir." },
        { q: "PSU koruma devreleri (OVP, UVP, OPP, SCP) nelerdir?", a: "Sırasıyla: Yüksek Voltaj, Düşük Voltaj, Aşırı Güç ve Kısa Devre korumalarıdır. Sistemin güvenliği için bu korumaların olması şarttır." },
        { q: "Single Rail (Tek Kanal) ve Multi Rail farkı nedir?", a: "Single Rail tüm gücü tek bir 12V hattından verir (OC için iyidir). Multi Rail gücü böler, bu da bir arıza durumunda daha güvenli olabilir." },
        { q: "PSU'da Japon kapasitör neden önemlidir?", a: "Japon üretimi kapasitörler yüksek ısıya daha dayanıklıdır ve çok daha uzun ömürlüdür." },
        { q: "Verimlilik (Efficiency) elektrik faturasını etkiler mi?", a: "Evet. %90 verimli bir PSU, %70 verimli bir PSU'ya göre prizden daha az elektrik çekerek aynı gücü sağlar." },
        { q: "PSU Tier List nedir?", a: "Dünya çapındaki uzmanların PSU'ları iç bileşen kalitesine göre A, B, C gibi sınıflara ayırdığı güvenilir bir sıralama listesidir." },
        { q: "Sistemim kaç Watt harcar?", a: "Çevrimiçi PSU hesaplayıcıları (be quiet!, OuterVision) kullanarak işlemci ve ekran kartınıza göre tahmini tüketimi bulabilirsiniz." },
        { q: "Geleceğe dönük PSU kaç Watt olmalı?", a: "Günümüzün orta-üst segment sistemleri için 750W veya 850W Gold bir PSU, uzun yıllar yeterli olacaktır." },
        { q: "PSU fanı neden bazen dönmüyor?", a: "Çoğu modern PSU'da 'Zero RPM' modu vardır. Yük altına girip belli bir sıcaklığa ulaşmadan fan dönmez, bu sayede sessiz çalışır." },
        { q: "SFX PSU nedir?", a: "Mini-ITX gibi çok küçük kasalar için tasarlanmış, standart ATX güç kaynaklarından çok daha küçük boyutlu ünitelerdir." },
        { q: "PSU'yu ters takarsam ne olur?", a: "Eğer kasanın altında hava boşluğu varsa fan aşağı bakmalıdır. Fan yukarı bakarsa içerideki sıcak havayı çeker, bu da PSU'nun daha çok ısınmasına neden olur." },
        { q: "PSU'dan gelen cızırtı sesi (Coil Whine) tehlikeli mi?", a: "Hayır, bobin titreşimidir. Performansa etkisi yoktur ama kulak tırmalayıcı olabilir." },
        { q: "Bilgisayar yük altındayken aniden kapanıyor?", a: "PSU gücü yetmiyor olabilir veya PSU aşırı ısınıp kendini korumaya alıyor olabilir." },
        { q: "PSU'nun içi açılıp temizlenmeli mi?", a: "KESİNLİKLE HAYIR! İçindeki kapasitörler fişten çekilse bile ölümcül düzeyde elektrik tutabilir. Sadece dışarıdan hava tutulmalıdır." },
        { q: "PSU ömrü kaç yıldır?", a: "Kaliteli bir PSU 7-10 yıl veya daha fazla sorunsuz çalışabilir. Garanti süreleri de genelde bu civardadır." },
        { q: "PSU patlar mı?", a: "Çok kalitesiz (merdiven altı) markalar yüksek yük altında kapasitör patlatabilir veya yanabilir." },
        { q: "PFC (Power Factor Correction) nedir?", a: "Elektrik şebekesinden çekilen gücün daha verimli ve temiz bir şekilde kullanılmasını sağlayan teknolojidir (Aktif PFC önerilir)." },
        { q: "Hold-up Time nedir?", a: "Elektrik kesildikten sonra PSU'nun sistemi ne kadar süre (milisaniye) açık tutabildiğidir. UPS (Kesintisiz Güç Kaynağı) geçişleri için önemlidir." },
        { q: "12V, 5V ve 3.3V kanalları neyi besler?", a: "12V işlemci ve ekran kartını, 5V ve 3.3V ise depolama birimlerini ve USB aygıtlarını besler." },
        { q: "PSU test cihazı nedir?", a: "PSU'yu bir bilgisayara bağlamadan tüm çıkış voltajlarının doğru olup olmadığını ölçen küçük bir cihazdır." },
        { q: "Sanal madencilik (Mining) için hangi PSU seçilmeli?", a: "7/24 çalışmaya uygun, verimliliği yüksek (Platinum/Titanium) ve yüksek Watt değerli modeller seçilmelidir." },
        { q: "RGB PSU mantıklı mı?", a: "PSU genellikle kasada kapalı bir bölmede durur, bu yüzden RGB olması görsel olarak pek fark edilmez." },
        { q: "PSU şalteri kapalıyken anakartta ışık yanar mı?", a: "Hayır, şalter fiziksel olarak tüm elektrik akışını keser." },
        { q: "Eski PSU yeni anakarta uyar mı?", a: "Soketler (24-pin vb.) uyumluysa uyar ancak eski PSU'larda yeni nesil işlemcilerin istediği ek güç kabloları eksik olabilir." },
        { q: "Kondansatör şişmesi nedir?", a: "PSU içindeki silindirik parçaların aşırı ısıdan dolayı üst kısımlarının bombelenmesidir; PSU'nun ölmek üzere olduğunun işaretidir." },
        { q: "Kablo kirliliği (Cable Management) neden önemli?", a: "Sadece görsellik değil, kasa içindeki hava akışının engellenmemesi için de önemlidir." },
        { q: "PSU fanı çok gürültülü çalışıyor?", a: "Fan bilyası bozulmuş olabilir veya PSU tozdan dolayı aşırı ısınıp fan devrini yükseltiyordur." },
        { q: "Fansız (Fanless) PSU var mı?", a: "Evet, tamamen pasif soğutmalı modeller vardır. Tamamen sessizdirler ancak genellikle düşük Watt değerlerinde olurlar." },
        { q: "PSU alırken ağırlık bir kalite göstergesi mi?", a: "Genellikle evet. İçindeki pasif soğutma bloklarının ve bakır bobinlerin kalitesi PSU'nun ağır olmasına neden olur." },
        { q: "Yandaki voltaj tablosu neyi anlatır?", a: "Hangi voltaj kanalından (12V, 5V vb.) maksimum kaç Amper akım verilebildiğini gösterir." },
        { q: "Molex kablosu nedir?", a: "Eski tip diskleri ve bazı kasa fanlarını beslemek için kullanılan, günümüzde popülerliğini yitiren 4 pinli kaba bağlantı tipidir." },
        { q: "EPS kablosu nedir?", a: "Genellikle işlemciyi besleyen 8-pinli (veya 4+4) güç kablosunun profesyonel adıdır." },
        { q: "SATA güç kablosu kaç cihaz besler?", a: "Tek bir kablo üzerinde genelde 3-4 adet SATA girişi bulunur, bunlar SSD ve HDD'leri besler." },
        { q: "PSU'da 'Ripple' nedir?", a: "DC çıkışındaki istenmeyen dalgalanmalardır. Ripple ne kadar düşükse donanımlar o kadar temiz elektrik alır." },
        { q: "Düşük Watt PSU ile yüksek ekran kartı takılırsa?", a: "Sistem oyun açtığı an veya ağır yüke girdiğinde PSU kapanır veya bilgisayar reset atar." },
        { q: "PSU kablolarındaki sleeve (örgü) kaplama ne işe yarar?", a: "Kabloların aşınmasını önler ve daha estetik görünmesini sağlar." },
        { q: "C13 ve C14 güç kablosu farkı?", a: "C14 PSU üzerindeki giriştir, C13 ise duvardaki prizden gelen kablonun ucudur (standart PC güç kablosu)." },
        { q: "PSU'da 'Relay Click' sesi nedir?", a: "Kaliteli PSU'larda açılış ve kapanışta gelen 'tık' sesidir; sistemin güvenle kapatıldığını gösteren röle sesidir." },
        { q: "Peak Power (Zirve Güç) nedir?", a: "PSU'nun saniyelik olarak çıkabileceği maksimum güçtür. Sürekli bu güçte çalışamaz." },
        { q: "PSU alırken garanti süresi neyi gösterir?", a: "Üreticinin ürününe olan güvenini gösterir. 10-12 yıl garanti veren markalar genelde en kaliteli bileşenleri kullanır." },
        { q: "Fiyatı çok ucuz 600W PSU alınır mı?", a: "Riskli. 'Everest, Frisby' gibi (etiket basılmış) çok ucuz ürünler genellikle vaat edilen gücü veremez ve koruma devreleri eksiktir." }
    ],
    "Kasa ve Soğutma (Hava / Sıvı)": [
        { q: "Mesh kasa nedir, neden tercih edilmelidir?", a: "Ön paneli delikli (ızgaralı) olan kasalardır. İçeriye taze hava girişini maksimize ederek bileşenlerin çok daha serin çalışmasını sağlar." },
        { q: "Full Tower, Mid Tower ve ITX kasa farkı?", a: "Kasaların boyutlarını ifade eder. Full Tower en büyüğüdür, Mid Tower standart oyuncu kasasıdır, ITX ise çok küçük ve kompakt sistemler içindir." },
        { q: "Temperli cam (Tempered Glass) patlar mı?", a: "Nadir de olsa ani sıcaklık değişimleri veya köşelerden alınan darbelerle patlayabilir. Akrilik panellere göre çok daha dayanıklı ve şıktır." },
        { q: "Kasa içi hava akışı (Airflow) nasıl olmalıdır?", a: "Genel kural; ön ve alttan soğuk hava içeri girmeli, arka ve üstten sıcak hava tahliye edilmelidir." },
        { q: "Pozitif ve Negatif basınç nedir?", a: "İçeri giren hava çıkan havadan fazlaysa pozitif (az tozlanır), çıkan hava fazlaysa negatif basınç oluşur (daha iyi soğutma ama çok tozlanır)." },
        { q: "Kule tipi soğutucu stok fandan neden iyidir?", a: "Daha büyük yüzey alanı ve ısı boruları (heatpipes) sayesinde ısıyı işlemciden çok daha hızlı uzaklaştırır ve daha sessiz çalışır." },
        { q: "Isı borusu (Heatpipe) sayısı neden önemlidir?", a: "Boru sayısı arttıkça ısı iletim kapasitesi artar. Üst seviye hava soğutmalarda genelde 6 veya daha fazla ısı borusu bulunur." },
        { q: "Statik Basınçlı fan ve Airflow fan farkı?", a: "Statik basınçlı fanlar havayı engellerin (radyatör/soğutucu blok) içinden geçirmek için, Airflow fanlar ise açık alanda hava taşımak için tasarlanmıştır." },
        { q: "Fanlardaki PWM (4-pin) özelliği nedir?", a: "İşlemci sıcaklığına göre fan hızının anakart tarafından otomatik olarak ayarlanmasını sağlayan teknolojidir." },
        { q: "Çift kuleli (Dual Tower) soğutucu nedir?", a: "İki ayrı metal blok ve ortasında/önünde iki fan bulunan, sıvı soğutma performansına yaklaşan devasa hava soğutuculardır." },
        { q: "AIO (All-in-One) sıvı soğutma nedir?", a: "Pompa, radyatör ve boruların fabrikadan hazır, bakımı kapalı bir şekilde geldiği tak-çalıştır sıvı soğutma sistemidir." },
        { q: "120, 240, 280 ve 360mm radyatör farkı?", a: "Radyatörün boyutunu ve üzerine takılan fan sayısını/boyutunu belirtir. Boyut arttıkça soğutma performansı artar." },
        { q: "Sıvı soğutma pompası neden ses yapar?", a: "İçinde hava kabarcığı kalmış olabilir veya pompa ömrünü tamamlıyor olabilir. Pompanın radyatörden daha aşağıda konumlanması önerilir." },
        { q: "Sıvı soğutma sızdırır mı?", a: "Modern AIO sistemlerde sızıntı riski çok düşüktür ancak çok eski veya hasarlı ünitelerde risk her zaman vardır." },
        { q: "Custom Loop (Özel Sıvı Soğutma) nedir?", a: "Kullanıcının boruları, rezervuarı ve pompayı tek tek seçip kendi kurduğu, en yüksek performanslı ve görselliği en iyi olan sistemdir." },
        { q: "Termal macun ne sıklıkla yenilenmelidir?", a: "Kullanıma bağlı olarak genellikle 1-2 yılda bir yenilenmesi, kuruyan macunun iletkenliğini kaybetmemesi için önerilir." },
        { q: "Sıvı metal (Liquid Metal) nedir?", a: "Standart macunlara göre çok daha yüksek iletkenlik sunan metalik alaşımdır. Elektriği ilettiği için uygulaması risklidir." },
        { q: "Termal ped (Thermal Pad) nerede kullanılır?", a: "Ekran kartı bellekleri, VRM'ler ve M.2 SSD'ler gibi doğrudan macun sürülemeyen parçaların soğutulmasında kullanılır." },
        { q: "Soğutucu altındaki plastik etiketi unutmak?", a: "En yaygın montaj hatasıdır. Unutulursa işlemci saniyeler içinde 100 dereceye çıkar ve sistem kapanır." },
        { q: "Pompa devri (RPM) her zaman %100 mü olmalı?", a: "Çoğu AIO üreticisi pompanın sabit ve yüksek devirde çalışmasını önerir, fanlar ise sıcaklığa göre değişebilir." },
        { q: "Daisy Chain fan bağlantısı nedir?", a: "Fanların birbirine eklenerek tek bir kablo üzerinden anakarta bağlanmasıdır; kablo kirliliğini büyük oranda azaltır." },
        { q: "Rulman tipleri (Hydraulic, Ball, MagLev) neyi değiştirir?", a: "Fanın ömrünü, ses seviyesini ve hangi pozisyonda (yatay/dikey) daha iyi çalışacağını belirler." },
        { q: "Reverse Blade (Ters Kanat) fan nedir?", a: "Havanın yönünü tersine çeviren fanlardır. Kasada 'şov' amaçlı, fanın güzel kısmının içeri bakmasını sağlarken hava çekmesine yarar." },
        { q: "Fan kontrolcü (Hub) ne işe yarar?", a: "Anakarttaki az sayıdaki fan girişini çoğaltarak çok sayıda fanı tek merkezden yönetmeyi sağlar." },
        { q: "Kasa fanı CFM değeri nedir?", a: "Fanın dakikada taşıdığı hava hacmidir. Bu değer ne kadar yüksekse fan o kadar çok hava üfler." },
        { q: "Kasa ne sıklıkla temizlenmelidir?", a: "Toz filtresi varsa 3 ayda bir filtre temizliği, 6-12 ayda bir ise detaylı iç temizlik önerilir." },
        { q: "Toz filtreleri hava akışını engeller mi?", a: "Evet, bir miktar engeller ancak bileşenlerin tozlanıp daha fazla ısınmasını önlediği için mutlaka kullanılmalıdır." },
        { q: "Kompresörle kasa temizlerken nelere dikkat edilmeli?", a: "Fanların dönmesine izin verilmemelidir; yüksek hızda dönen fanlar elektrik üreterek anakarta zarar verebilir." },
        { q: "Sıvı soğutma sıvısı biter mi?", a: "AIO sistemlerde sıvı zamanla mikroskobik düzeyde buharlaşabilir ancak 5-7 yıl boyunca müdahale gerektirmez." },
        { q: "Kasa camı nasıl temizlenmeli?", a: "Mikrofiber bez ve alkol içermeyen temizleyicilerle. Sert bezler temperli camı çizebilir." },
        { q: "Radyatör kasanın neresine takılmalı?", a: "En ideal yer kasanın üstüdür (egzoz olarak). Ön tarafa takılacaksa borular aşağıda kalacak şekilde takılması hava kabarcığı sesini önler." },
        { q: "Push-Pull konfigürasyonu nedir?", a: "Radyatörün hem önüne hem arkasına fan takarak havayı hem itip hem çekmektir; soğutma performansını artırır." },
        { q: "Low-Profile soğutucu nedir?", a: "Çok ince kasalar (HTPC, ITX) için tasarlanmış, yüksekliği çok az olan özel hava soğutuculardır." },
        { q: "Vapor Chamber (Buhar Odası) nedir?", a: "Üst seviye ekran kartlarında ve soğutucularda bulunan, ısı borularından daha etkili olan geniş yüzeyli ısı yayma teknolojisidir." },
        { q: "Eski bir sıvı soğutma yeni sokete uyar mı?", a: "Üreticiden uygun montaj braketi (kit) satın alınarak yeni soketlere (LGA1700, AM5) uyumlu hale getirilebilir." },
        { q: "Laptop soğutucu standlar işe yarar mı?", a: "Laptopun altındaki hava girişlerini açtığı için 3-7 derece arası bir düşüş sağlayabilir ancak mucize yaratmaz." },
        { q: "Fan gürültüsü nasıl azaltılır?", a: "BIOS üzerinden 'Silent' (Sessiz) profil seçilerek veya fanların altına titreşim önleyici kauçuklar konularak." },
        { q: "Pasif soğutma (Passive Cooling) nedir?", a: "Hiç fan kullanmadan, sadece devasa metal bloklar (heatsink) yardımıyla yapılan tamamen sessiz soğutmadır." },
        { q: "Kasa arkasındaki kablo boşluğu neden var?", a: "Kablo kirliliğini arkaya gizlemek ve ana bölümde hava akışını engelleyecek unsurları ortadan kaldırmak için." },
        { q: "Dikey ekran kartı takma aparatı ısıyı etkiler mi?", a: "Kart cama çok yaklaşırsa hava alamaz ve sıcaklık 10-15 derece artabilir." },
        { q: "PWM fan çoklayıcı kullanmak anakarta zarar verir mi?", a: "Tek bir girişe 3'ten fazla yüksek akımlı fan takmak girişi yakabilir; bu durumda harici güç beslemeli hub kullanılmalıdır." },
        { q: "Kasa ayakları neden yüksek olmalı?", a: "Güç kaynağının (PSU) alttan rahatça soğuk hava çekebilmesi için kasanın yerden yüksek olması şarttır." },
        { q: "Fanlardaki dBA değeri nedir?", a: "Fanın çıkardığı ses seviyesidir. 20-25 dBA sessiz, 40+ dBA ise gürültülü kabul edilir." },
        { q: "Isı iletkenlik katsayısı (W/mK) nedir?", a: "Termal macunun ısıyı ne kadar iyi ilettiğini gösteren birimdir. Rakam büyüdükçe performans artar." },
        { q: "Su bloğu (Water Block) nedir?", a: "Sıvı soğutmada işlemciye veya GPU'ya temas eden, içinden suyun geçtiği bakır/nikel parçadır." },
        { q: "Soğutucuda bakır mı alüminyum mu?", a: "Bakır ısıyı daha hızlı iletir, alüminyum ise ısıyı havaya daha hızlı dağıtır. En iyi soğutucularda her ikisi de kullanılır." },
        { q: "Fan yönü nasıl anlaşılır?", a: "Fanın yan tarafındaki ok işaretlerinden veya motorun bulunduğu (tellerin geçtiği) kısmın havanın çıktığı yer olmasından anlaşılır." },
        { q: "RGB kontrolü için hangi yazılımlar kullanılır?", a: "Anakart markasına göre; Aura Sync, Mystic Light, RGB Fusion veya evrensel olan OpenRGB kullanılabilir." },
        { q: "Sıvı soğutma radyatörü neden tozlanır?", a: "Sık dizilmiş metal yapraklar (fins) tozu tutar; bu da hava geçişini engelleyerek soğutmayı bozar." },
        { q: "Kasa seçiminde ekran kartı uzunluğu (GPU Clearance)?", a: "Satın alacağınız kasanın, ekran kartınızın uzunluğunu (mm cinsinden) desteklediğinden emin olmalısınız; yoksa kart sığmaz." }
    ],
    "Monitör Teknolojileri (Panel, Hz, MS)": [
        { q: "Yenileme Hızı (Hz) nedir?", a: "Ekranın saniyede kaç kez güncellendiğini gösterir. Hz ne kadar yüksekse hareketler o kadar akıcı görünür (Örn: 144Hz, 240Hz)." },
        { q: "Tepki Süresi (ms) neden önemlidir?", a: "Bir pikselin bir renkten diğerine geçme hızıdır. Düşük ms (Örn: 1ms), hızlı sahnelerde 'ghosting' (hayalet görüntü) oluşmasını engeller." },
        { q: "Çözünürlük (1080p, 2K, 4K) farkı nedir?", a: "Ekrandaki toplam piksel sayısıdır. Çözünürlük arttıkça görüntü keskinleşir ancak ekran kartına binen yük de artar." },
        { q: "İnç ve PPI dengesi nasıl olmalı?", a: "24 inç için 1080p, 27 inç için 2K (1440p), 32 inç ve üzeri için 4K çözünürlük ideal keskinliği (PPI) sağlar." },
        { q: "Ghosting (Gölge) testi nasıl yapılır?", a: "UFO Test (testufo.com) sitesi üzerinden ekranın hareketli nesnelerdeki netliği kontrol edilebilir." },
        { q: "IPS panelin avantajı nedir?", a: "En iyi renk doğruluğunu ve en geniş izleme açılarını sunar. Tasarımcılar ve görsel kalite isteyen oyuncular için idealdir." },
        { q: "VA panel nedir, kimler almalı?", a: "Yüksek kontrast oranı ve derin siyahlar sunar. Film izlemek ve karanlık atmosferli oyunlar için çok uygundur." },
        { q: "TN panel hala alınır mı?", a: "Sadece çok düşük bütçeli veya çok yüksek hız (540Hz gibi) arayan profesyonel E-sporcular için hız avantajı nedeniyle tercih edilebilir." },
        { q: "OLED monitörlerin farkı nedir?", a: "Her piksel kendi ışığını yakar. Sonsuz kontrast, gerçek siyahlar ve neredeyse 0ms tepki süresi sunar; teknolojinin zirvesidir." },
        { q: "QLED (Quantum Dot) nedir?", a: "Standart LCD panellerin üzerine eklenen bir katman sayesinde çok daha parlak ve canlı renkler elde edilmesini sağlayan teknolojidir." },
        { q: "G-Sync ve FreeSync nedir?", a: "Ekran kartının ürettiği kare sayısı ile monitörün Hz değerini eşitleyerek ekrandaki yırtılmaları (tearing) önleyen teknolojilerdir." },
        { q: "G-Sync Compatible ne demek?", a: "Aslında FreeSync olan bir monitörün, NVIDIA tarafından test edilip RTX kartlarla da sorunsuz çalıştığının onaylanmasıdır." },
        { q: "HDR (High Dynamic Range) nedir?", a: "Görüntüdeki en parlak ve en karanlık kısımlar arasındaki detay farkını artırarak daha gerçekçi bir görüntü sunar." },
        { q: "HDR 400, 600, 1000 farkı nedir?", a: "Ekranın çıkabildiği maksimum parlaklık seviyesini (nit) belirtir. Sayı arttıkça HDR deneyimi çok daha etkileyici olur." },
        { q: "PWM Dimming nedir?", a: "Ekran parlaklığını ışığı hızlıca açıp kapatarak ayarlamaktır. Hassas gözlerde yorgunluk ve baş ağrısı yapabilir (Flicker-Free önerilir)." },
        { q: "HDMI 2.1 neden önemli?", a: "4K çözünürlükte 120Hz/144Hz gibi yüksek hızları ve dinamik HDR desteğini tek kablo üzerinden sağlayabilir." },
        { q: "DisplayPort (DP) vs HDMI?", a: "PC oyuncuları için genellikle DisplayPort daha iyidir çünkü G-Sync/FreeSync desteği ve yüksek Hz uyumluluğu daha geniştir." },
        { q: "Type-C üzerinden görüntü alınır mı?", a: "Evet, 'DisplayPort Alt Mode' destekleyen Type-C portları üzerinden tek kabloyla hem görüntü aktarımı hem de laptop şarjı yapılabilir." },
        { q: "DSC (Display Stream Compression) nedir?", a: "Yüksek çözünürlük ve Hz verisini kalite kaybı olmadan sıkıştırarak kablo bant genişliğine sığdıran teknolojidir." },
        { q: "HDCP nedir?", a: "Dijital içerik korumasıdır. Netflix veya Blu-ray gibi içerikleri yüksek çözünürlükte izlemek için monitörün HDCP uyumlu olması gerekir." },
        { q: "Kavisli (Curved) monitör gerekli mi?", a: "Özellikle geniş (Ultrawide) ekranlarda gözün ekranın köşelerine olan mesafesini eşitleyerek daha derin bir görüş alanı sağlar." },
        { q: "Ultrawide (21:9) monitör avantajı?", a: "Daha geniş bir görüş açısı sunar; hem iş üretkenliğinde (yanyana pencereler) hem de simülasyon oyunlarında çok etkilidir." },
        { q: "Pivot özelliği nedir?", a: "Monitörün kendi standı üzerinde 90 derece döndürülerek dikey konuma getirilmesidir; kod yazanlar ve okuma yapanlar için harikadır." },
        { q: "Vesa desteği nedir?", a: "Monitörün arkasındaki standart vida yuvalarıdır. Bu sayede monitörü duvar aparatına veya hareketli bir kola takabilirsiniz." },
        { q: "Mavi Işık Filtresi işe yarar mı?", a: "Evet, akşam kullanımlarında göz yorgunluğunu azaltır ve uyku kalitesini korumaya yardımcı olur." },
        { q: "Ölü Piksel (Dead Pixel) nasıl anlaşılır?", a: "Ekranı tamamen siyah, beyaz, kırmızı, yeşil ve mavi yaparak farklı renklerde parlamayan veya sürekli yanan nokta olup olmadığına bakılır." },
        { q: "Işık Sızması (Backlight Bleed) nedir?", a: "Özellikle IPS panellerde, karanlık ortamda ekranın köşelerinden beyaz ışık sızması durumudur." },
        { q: "OLED Burn-in (Yanma) nedir?", a: "Ekranda çok uzun süre sabit kalan görüntülerin (logo, taskbar) panelde kalıcı iz bırakmasıdır. Yeni nesil OLED'lerde bu risk azalmıştır." },
        { q: "Ekran neden 'No Signal' hatası verir?", a: "Kablo tam oturmamış olabilir, yanlış giriş seçilmiş olabilir veya ekran kartı görüntü vermiyor olabilir." },
        { q: "Monitörde Coil Whine olur mu?", a: "Evet, bazı monitörlerin içindeki güç devrelerinden veya parlaklık ayarından dolayı ince bir çınlama sesi gelebilir." },
        { q: "Local Dimming (Yerel Karartma) nedir?", a: "Arka aydınlatmanın bölgelere ayrılıp sadece gerekli yerlerin söndürülmesidir; siyah kalitesini ve HDR'ı iyileştirir." },
        { q: "DCI-P3 ve sRGB farkı?", a: "Renk gamutlarıdır. sRGB standart internet içeriğidir, DCI-P3 ise çok daha geniş ve sinematik bir renk yelpazesini kapsar." },
        { q: "Delta E değeri nedir?", a: "Renk sapma miktarıdır. Delta E < 2 olan monitörler, insan gözünün fark edemeyeceği kadar doğru renkler sunar." },
        { q: "Flicker-Free teknolojisi nedir?", a: "Ekranın titremesini engelleyerek uzun süreli kullanımlarda göz yanması ve yorgunluğunu önleyen teknolojidir." },
        { q: "Mat ekran mı Parlak ekran mı?", a: "Mat ekran yansımaları önler (ofis/oyun için iyi), parlak ekran renkleri daha canlı gösterir (film/tasarım için iyi)." },
        { q: "Overdrive ayarı ne işe yarar?", a: "Tepki süresini iyileştirmek için piksellere fazla voltaj verilir. Çok yüksek ayarda 'Inverse Ghosting' (ters gölge) oluşabilir." },
        { q: "Black Stabilizer nedir?", a: "Oyunlardaki çok karanlık bölgelerin parlaklığını artırarak düşmanların daha rahat görünmesini sağlayan yazılımsal özelliktir." },
        { q: "VRR (Variable Refresh Rate) nedir?", a: "Değişken yenileme hızıdır; konsollarda ve PC'de yırtılmasız oyun deneyimi için genel teknolojinin adıdır." },
        { q: "10-Bit (1.07 Milyar Renk) panel farkı?", a: "8-bit panellere göre renk geçişlerinin (banding) çok daha pürüzsüz ve doğal görünmesini sağlar." },
        { q: "Mini-LED nedir?", a: "Binlerce küçük LED ile aydınlatma yapılmasıdır. OLED'e yakın siyahlar ve çok yüksek parlaklık sunar, yanma riski yoktur." },
        { q: "Dikey Tarama Frekansı nedir?", a: "Monitörün saniyede kaç kez yukarıdan aşağıya tarandığıdır; Hz değeri ile aynı şeyi ifade eder." },
        { q: "Gecikme Süresi (Input Lag) nedir?", a: "Klavye/mouse komutunun ekrana yansıma süresidir. Panel tepki süresinden (ms) farklı ve daha kapsamlı bir değerdir." },
        { q: "Monitör overclock edilir mi?", a: "Bazı monitörler menüsünden veya ekran kartı ayarlarından birkaç Hz (Örn: 144'ten 165'e) artırılabilir ancak panel ömrünü etkileyebilir." },
        { q: "Anti-Glare kaplama nedir?", a: "Ekran yüzeyindeki yansıma önleyici özel katmandır; pencere karşısında kullanımda kolaylık sağlar." },
        { q: "Kensington Kilidi nedir?", a: "Monitörün çalınmasını önlemek için arkasına takılan çelik kablo yuvasıdır." },
        { q: "Crosshair (Nişangah) özelliği nedir?", a: "Monitörün kendi yazılımı ile ekranın tam ortasına fiziksel bir nişangah koymasıdır." },
        { q: "PIP ve PBP nedir?", a: "İki farklı cihazdan (PC ve Laptop gibi) gelen görüntüyü aynı anda ekranda farklı pencerelerde görme özelliğidir." },
        { q: "Dithering (FRC) nedir?", a: "8-bit bir panelin pikselleri hızlı titreterek 10-bit gibi görünmesini sağlamasıdır (8-bit + FRC)." },
        { q: "Monitör temizleme spreyi zararlı mı?", a: "Alkol ve amonyak içermeyen, ekranlar için özel üretilmiş spreyler mikrofiber bezle kullanıldığında güvenlidir." },
        { q: "Hz değeri Windows ayarlarından neden yapılmalı?", a: "Yüksek Hz bir monitör taksanız bile Windows varsayılan olarak 60Hz açabilir; ayarlardan manuel olarak yükseltilmelidir." }
    ],
    "Çevre Birimleri (Klavye, Mouse, Kulaklık)": [
        { q: "DPI (Dots Per Inch) nedir?", a: "Farenin hassasiyetidir. Yüksek DPI, farenin en küçük hareketi ekranda daha büyük mesafeye taşımasını sağlar." },
        { q: "Polling Rate (Raporlama Hızı) nedir?", a: "Farenin saniyede kaç kez bilgisayara konum bilgisi gönderdiğidir. 1000Hz standarttır, yüksek değerler gecikmeyi azaltır." },
        { q: "Optik sensör mü, Lazer sensör mü?", a: "Oyunlar için optik sensörler daha tutarlıdır. Lazer sensörler cam gibi yüzeylerde çalışabilir ancak oyunlarda sapma yapabilir." },
        { q: "Mouse ağırlığı önemli mi?", a: "FPS oyuncuları genelde hızlı manevra için hafif (60-80g) fareleri, tasarımcılar ve MMO oyuncuları ise stabilite için ağır fareleri tercih eder." },
        { q: "IPS ve G (Hızlanma) değeri nedir?", a: "Sensörün ne kadar hızlı hareketi (IPS) ve ani hızlanmayı (G) hatasız takip edebileceğini gösterir." },
        { q: "PTFE Mouse ayakları (Skates) nedir?", a: "Farenin yüzeyde sürtünmeden kaymasını sağlayan teflon benzeri materyaldir; beyaz renkli olanlar genelde daha kalitelidir." },
        { q: "Mouse Grip (Tutuş) tipleri nelerdir?", a: "Palm (avuç içi), Claw (pençe) ve Fingertip (parmak ucu). Mouse seçimi bu tutuş şekline göre yapılmalıdır." },
        { q: "Mekanik klavye ile membran farkı nedir?", a: "Membran klavyeler tek bir lastik katman kullanırken, mekanik klavyeler her tuş için ayrı bir fiziksel anahtar (switch) kullanır. Mekanikler daha uzun ömürlü ve hızlıdır." },
        { q: "Switch renkleri (Red, Blue, Brown) ne anlama gelir?", a: "Red: Sessiz ve lineer (oyun için). Blue: Sesli ve klikli (yazı için). Brown: İkisinin ortası (hem oyun hem yazı)." },
        { q: "Anti-Ghosting ve N-Key Rollover nedir?", a: "Aynı anda çok fazla tuşa basıldığında, tüm basılan tuşların bilgisayar tarafından hatasız algılanması özelliğidir." },
        { q: "Hot-Swappable klavye nedir?", a: "Lehimleme yapmadan, klavyenin switchlerini sadece bir aparatla çekip yenisiyle değiştirebilme özelliğidir." },
        { q: "PBT ve ABS Keycap farkı?", a: "ABS plastik zamanla parlar ve aşınır. PBT daha serttir, parlamaz ve dokulu yapısını yıllarca korur." },
        { q: "Yüzde kaçlık klavye almalıyım?", a: "Full Size (%100) her şeyi içerir. TKL (%80) numpad içermez (mouse alanı açar). %60 ise sadece ana harfleri içerir (maksimum taşınabilirlik)." },
        { q: "Optik Switch nedir?", a: "Fiziksel temas yerine ışık kesilmesiyle çalışan switch türüdür. Metal aşınması olmadığı için çok daha hızlı ve uzun ömürlüdür." },
        { q: "7.1 Sanal Surround ses nedir?", a: "Sesi yazılımsal olarak işleyip 7 farklı yönden geliyormuş gibi hissettirerek oyunlarda düşman konumunu bulmayı kolaylaştıran teknolojidir." },
        { q: "Empedans (Ohm) değeri nedir?", a: "Kulaklığın elektrik direncidir. Yüksek Ohm değerli (80-250+) kulaklıklar için harici bir ses kartı veya amfi gerekebilir." },
        { q: "Açık (Open-Back) ve Kapalı (Closed-Back) kulaklık?", a: "Kapalı kulaklık sesi dışarı vermez (izolasyon sağlar). Açık kulaklık daha doğal bir ses sahnesi sunar ancak dışarıya ses verir." },
        { q: "Sürücü (Driver) boyutu ses kalitesini etkiler mi?", a: "Genelde 40mm veya 50mm kullanılır. Daha büyük sürücü, daha güçlü baslar üretebilir ancak tek başına kalite göstergesi değildir." },
        { q: "Kulaklıktaki 'Gürültü Engelleme' (ANC) nedir?", a: "Dışarıdaki motor, klima gibi düşük frekanslı sesleri mikrofonla analiz edip ters dalga göndererek yok etme teknolojisidir." },
        { q: "Kablosuz (Wireless) ekipmanlarda gecikme olur mu?", a: "Modern 2.4 GHz (dongle) bağlantılarda gecikme artık kablolu ile aynı seviyededir. Bluetooth ise hala oyun için gecikmelidir." },
        { q: "Mouse'larda batarya mı pil mi?", a: "Şarj edilebilir batarya hafiftir; kalem pil (AA/AAA) ise bittiğinde anında değiştirilip beklemeden devam etme avantajı sunar." },
        { q: "Bluetooth ve 2.4 GHz farkı?", a: "2.4 GHz oyunlar için hızlı ve stabil bir bağlantıdır. Bluetooth ise pil tasarrufu sağlar ve telefon/tablet uyumluluğu sunar." },
        { q: "Mousepad neden önemli?", a: "Sensörün zemini daha iyi okumasını sağlar ve farenin ayaklarının aşınmasını önler. 'Speed' (hız) ve 'Control' (kontrol) tipleri vardır." },
        { q: "Klavye nasıl temizlenir?", a: "Keycap'ler sökülüp sabunlu suda yıkanabilir. Gövde ise basınçlı hava ve fırça ile tozdan arındırılmalıdır." },
        { q: "Mouse 'Spin-out' hatası nedir?", a: "Hızlı hareket ettirince imlecin aniden gökyüzüne veya yere bakmasıdır; genelde kalitesiz sensörlerde görülür." },
        { q: "Ekipmanlarda RGB aydınlatma performansı etkiler mi?", a: "Donanım olarak etkilemez ancak kablosuz cihazlarda pil ömrünü ciddi oranda (yarı yarıya) kısaltabilir." },
        { q: "Yazılım (Software) desteği gerekli mi?", a: "Makro atamaları, DPI basamakları ve RGB senkronizasyonu için markanın kendi yazılımını kullanmak avantajlıdır." },
        { q: "Double-Click (Çift Tıklama) sorunu neden olur?", a: "Mouse içindeki mekanik anahtarın (switch) aşınması sonucu basışı iki kez iletmesidir. Optik switchli farelerde bu sorun olmaz." },
        { q: "Klavye 'Lubing' (Yağlama) nedir?", a: "Mekanik switch ve stabilizatörlere özel yağ sürerek sürtünme sesini azaltma ve basış hissiyatını pürüzsüzleştirme işlemidir." },
        { q: "Mikrofon 'Gain' ayarı nedir?", a: "Mikrofonun hassasiyet seviyesidir. Çok yüksek açılırsa arkadaki dip sesleri ve cızırtıyı da alır." },
        { q: "Ekipman alırken 'Ergonomi' neden ilk sırada olmalı?", a: "Çok güçlü bir donanımınız olsa bile, elinize uymayan bir mouse veya konforsuz kulaklık uzun vadede sağlık sorunları yaratabilir." },
        { q: "Sanal 7.1 mi gerçek 7.1 mi?", a: "Gerçek 7.1 kulaklıkların içinde çok sayıda küçük sürücü vardır ama ağırdır. Günümüzde sanal 7.1 yazılımları çok daha başarılı sonuçlar verir." },
        { q: "Mouse 'Lift-off Distance' (LOD) nedir?", a: "Farenin yerden ne kadar kaldırıldığında okumayı keseceğidir. Düşük LOD, fareyi kaldırıp düzelten oyuncular için daha iyidir." },
        { q: "Örgü kablo mu kauçuk kablo mu?", a: "Örgü kablo daha dayanıklıdır ancak daha sert olabilir. Yumuşak kauçuk (paracord benzeri) kablolar hareket özgürlüğü için daha iyidir." },
        { q: "Klavye 'Stabilizer' nedir?", a: "Space, Enter gibi büyük tuşların sallanmadan, her noktasından aynı şekilde basılmasını sağlayan mekanizmadır." },
        { q: "Mousepad temizliği nasıl yapılır?", a: "Ilık su ve çok az bulaşık deterjanı ile lifli olmayan bir bezle silinip, oda sıcaklığında kurumaya bırakılmalıdır." },
        { q: "Kulaklık pedleri soyulursa ne yapılır?", a: "Suni deri (protein leather) zamanla soyulur. Yedek kumaş veya kadife ped alarak kulaklığı yenileyebilirsiniz." },
        { q: "Makro tuşları yasak mı?", a: "Tek oyunculu oyunlarda serbesttir ancak rekabetçi online oyunlarda bazı karmaşık makrolar ban sebebi olabilir." },
        { q: "Polling rate 8000Hz gerekli mi?", a: "Çok yüksek Hz değerli monitörünüz (360Hz+) ve güçlü işlemciniz varsa fark edilebilir; standart kullanıcı için 1000Hz yeterlidir." },
        { q: "Hall Effect switch nedir?", a: "Mıknatıs teknolojisi ile çalışan switchlerdir. Tuşun ne kadar basıldığını milimetrik algılar (hızlı tetikleme sağlar)." },
        { q: "Ses kartı (DAC/AMP) ne zaman alınmalı?", a: "Anakartın dahili sesi yetersiz kalıyorsa veya yüksek empedanslı stüdyo kulaklığı kullanılıyorsa alınmalıdır." },
        { q: "Mouse 'Angle Snapping' nedir?", a: "Sensörün hareketi dümdüz bir çizgiye zorlamasıdır. Grafik tasarımda işe yarayabilir ama oyunlarda nişan almayı zorlaştırır." },
        { q: "Ekipman alırken 'Latency' (Gecikme) değerlerine nereden bakılır?", a: "RTINGS gibi profesyonel inceleme siteleri ekipmanların ms cinsinden gerçek gecikme değerlerini ölçer." },
        { q: "Klavye 'Plate' materyalleri (Steel, Brass, FR4)?", a: "Klavyenin içindeki plaka çelikse sert, FR4 ise daha esnek ve tok bir yazı yazma sesi verir." },
        { q: "Kulaklıkta 'Sidetone' özelliği nedir?", a: "Kendi sesinizi kulaklıktan duymanızı sağlar; böylece bağırarak konuşmanızı engeller." },
        { q: "Mouse sensörü neden takılır?", a: "Zeminde kıl/toz olabilir veya sensör merceği kirlenmiş olabilir. Alkol içermeyen bir kulak çubuğuyla temizlenebilir." },
        { q: "Hangi bağlantı tipi daha uzun pil ömrü sunar?", a: "Bluetooth bağlantısı, 2.4 GHz kablosuz bağlantıya göre çok daha az enerji tüketir." },
        { q: "Klavye 'Polling Rate' önemli mi?", a: "Genelde 1000Hz standarttır. Hızlı ritim oyunları (Osu! vb.) oynamıyorsanız daha fazlası hissedilmez." },
        { q: "Mouse 'Smoothing' nedir?", a: "Sensör verisinin yazılımsal olarak yumuşatılmasıdır. Hareket daha akıcı görünür ama 'input lag' ekler, oyunlarda kapatılmalıdır." },
        { q: "Yüksek sesle oyun oynamak kulaklığa zarar verir mi?", a: "Ekstrem ses seviyeleri sürücülerin (diyaframın) yırtılmasına veya seste bozulmalara (distorsiyon) neden olabilir." }
    ],
    "Yazılım ve Oyun Teknolojileri": [
        { q: "FPS nedir, kaç olmalı?", a: "Frames Per Second (Saniyedeki Kare Sayısı). 30 FPS oynanabilir, 60 FPS akıcı, 144 FPS ve üzeri ise profesyonel/rekabetçi standarttır." },
        { q: "Input Lag (Giriş Gecikmesi) nasıl azaltılır?", a: "V-Sync kapatılarak, 'NVIDIA Reflex' veya 'AMD Anti-Lag' özellikleri açılarak ve kablolu ekipman kullanılarak azaltılır." },
        { q: "Windows 'Oyun Modu' işe yarar mı?", a: "Evet, arka plan etkinliklerini kısıtlayarak sistem kaynaklarını oyuna önceliklendirir. Genellikle açık kalması önerilir." },
        { q: "Darboğaz yazılımla çözülür mi?", a: "Tamamen çözülmez ancak oyun ayarlarını (grafikleri) yükselterek yükü işlemciden ekran kartına kaydırmak darboğaz hissini azaltabilir." },
        { q: "DSR ve VSR nedir?", a: "Ekran kartının oyunu monitör çözünürlüğünden daha yüksekte işleyip sonra ekrana sığdırmasıdır; görüntüyü çok keskinleştirir." },
        { q: "DLSS nedir?", a: "NVIDIA'nın yapay zeka kullanarak düşük çözünürlüklü görüntüyü yüksek kaliteye yükseltmesi ve FPS'i devasa artırmasıdır." },
        { q: "FSR ve XeSS nedir?", a: "FSR (AMD) ve XeSS (Intel), DLSS'in rakipleridir. Çoğu ekran kartında çalışırlar ve benzer şekilde FPS artışı sağlarlar." },
        { q: "Frame Generation (Kare Oluşturma) nedir?", a: "Yapay zekanın mevcut iki kare arasına 'sahte' bir kare ekleyerek akıcılığı iki katına çıkarmasıdır (DLSS 3 / FSR 3)." },
        { q: "Ray Tracing (Işın İzleme) nedir?", a: "Işığın gerçek dünyadaki gibi yansıma, kırılma ve gölge hesaplamalarını yaparak oyunun sinematik görünmesini sağlayan teknolojidir." },
        { q: "Ray Reconstruction nedir?", a: "Işın izleme sırasında oluşan kumlanmayı (noise) yapay zeka ile temizleyerek çok daha net yansımalar sunan NVIDIA teknolojisidir." },
        { q: "DDU (Display Driver Uninstaller) nedir?", a: "Ekran kartı sürücülerini sistemden hiçbir kalıntı bırakmadan silmeye yarayan profesyonel bir araçtır." },
        { q: "WHQL sürücü ne demek?", a: "Microsoft tarafından test edilip onaylanmış, en stabil olduğu garanti edilen sürücü sürümüdür." },
        { q: "Sürücü güncellemek FPS artırır mı?", a: "Özellikle yeni çıkan oyunlarda 'Game Ready' sürücüleri %20'ye varan performans artışı ve hata düzeltmeleri sağlayabilir." },
        { q: "BIOS güncellemek riskli mi?", a: "Güncelleme sırasında elektrik kesilmezse risk düşüktür. Yeni işlemci desteği ve sistem kararlılığı için gereklidir." },
        { q: "Chipset sürücüsü nedir?", a: "Anakart üzerindeki bileşenlerin (USB, SATA, PCIe) işlemciyle en verimli şekilde iletişim kurmasını sağlayan yazılımdır." },
        { q: "Anti-Aliasing (Kenar Yumuşatma) nedir?", a: "Nesnelerin kenarlarındaki tırtıklı (merdiven gibi) görünümü yok ederek görüntüyü pürüzsüzleştirme işlemidir." },
        { q: "V-Sync (Dikey Senkronizasyon) neden açılır?", a: "Ekran yırtılmalarını önlemek için FPS'i monitörün Hz değerine sabitler ancak giriş gecikmesi (input lag) ekler." },
        { q: "Texture Quality FPS'i çok etkiler mi?", a: "VRAM'iniz yeterliyse FPS'i az etkiler, ancak VRAM dolarsa sistemde büyük takılmalara (stutter) neden olur." },
        { q: "Motion Blur neden kapatılmalı?", a: "Hızlı hareketlerde görüntüyü bulanıklaştırır. Rekabetçi oyunlarda düşmanları görmeyi zorlaştırdığı için genellikle kapatılır." },
        { q: "Field of View (FOV) nedir?", a: "Karakterinizin ekranda gördüğü açının genişliğidir. Yüksek FOV daha çok alanı görmenizi sağlar ancak performans yükü artabilir." },
        { q: "Hangi Windows sürümü oyun için daha iyi?", a: "Windows 11, yeni nesil işlemci mimarileri (Intel 12. Nesil+) ve DirectStorage desteği nedeniyle şu an en iyi seçenektir." },
        { q: "Bloatware nedir?", a: "Windows veya laptop üreticisiyle gelen, sistemi yavaşlatan gereksiz yüklü yazılımlardır." },
        { q: "Task Manager'da (Görev Yöneticisi) 'CPU 100%' olması normal mi?", a: "Boştayken normal değildir; arkada işlemciyi yoran bir virüs veya hatalı çalışan bir program olabilir." },
        { q: "Sanal Bellek (Pagefile) kapatılmalı mı?", a: "Hayır. RAM'iniz çok olsa bile bazı programlar buna ihtiyaç duyar. Windows'un yönetmesine bırakmak en güvenlisidir." },
        { q: "DirectX 12 ve Vulkan farkı?", a: "Her ikisi de düşük seviyeli API'lardır. Donanımı daha verimli kullanırlar. Bazı oyunlar Vulkan'da, bazıları DX12'de daha iyi çalışır." },
        { q: "Benchmark nedir?", a: "Bilgisayarın performansını ölçmek için yapılan standart testlerdir (Örn: Cinebench, 3DMark, Furmark)." },
        { q: "Overclock (Hız Aşırtma) garantiyi bozar mı?", a: "Genellikle evet, ancak yazılımsal olarak yapıldığında tespit edilmesi zordur. Donanıma fiziksel müdahale edilmediği sürece çoğu kullanıcı yapar." },
        { q: "Undervolt nedir?", a: "Parçaya giden voltajı, performansı düşürmeden azaltmaktır. Isınmayı ve güç tüketimini ciddi oranda düşürür." },
        { q: "Stutter (Takılma) neden olur?", a: "Yetersiz RAM, yavaş disk hızı (HDD kullanımı) veya ani CPU kullanım sıçramaları takılmalara neden olur." },
        { q: "XMP/EXPO açılmazsa ne olur?", a: "RAM'leriniz 6000MHz olsa bile 4800MHz gibi temel hızlarda çalışır ve büyük performans kaybı yaşarsınız." },
        { q: "Re-Size BAR nedir?", a: "İşlemcinin ekran kartı belleğine (VRAM) tek seferde tam erişim sağlamasıdır; %5-10 arası FPS artışı sağlayabilir." },
        { q: "Shader Compilation (Gölgelendirici Derleme) nedir?", a: "Oyunun başında yapılan, oyun içindeki takılmaları önlemek için görsellerin işlemci tarafından önceden hazırlanmasıdır." },
        { q: "Min %1 ve %0.1 FPS nedir?", a: "Oyunun ne kadar stabil olduğunu gösterir. Ortalama FPS yüksek olsa bile bunlar düşükse oyun 'akıcı' hissettirmez." },
        { q: "Isınan bir işlemciyi yazılımla soğutmak mümkün mi?", a: "Fan hızlarını artırarak (Fan Curve) veya güç limitlerini (TDP) kısıtlayarak sıcaklık düşürülebilir." },
        { q: "G-Sync aktif mi nasıl anlaşılır?", a: "Monitör menüsünden Hz değerinin oyun içindeki FPS ile birlikte anlık değişip değişmediğine bakarak anlaşılabilir." },
        { q: "Sistem neden aniden yeniden başlar?", a: "Genellikle güç kaynağı (PSU) yetersizliği veya aşırı ısınma koruması (Thermal Shutdown) nedeniyle olur." },
        { q: "DLL dosyası hatası nasıl çözülür?", a: "İlgili Microsoft Visual C++ paketlerini veya DirectX Web Runtime yazılımını yükleyerek çözülür." },
        { q: "Ping nedir, nasıl düşürülür?", a: "Verinin sunucuya gidip gelme süresidir. Ethernet kablosu kullanmak ve arka planda indirme yapmamak pingi düşürür." },
        { q: "Bottleneck Calculator siteleri güvenilir mi?", a: "Hayır, bu siteler yapay rakamlar verir. Gerçek oyun testlerini (YouTube incelemeleri) izlemek çok daha doğrudur." },
        { q: "Ekran kartı 'Artifact' vermesi nedir?", a: "Ekranda beliren çizgiler veya bozuk renkli karelerdir; GPU belleğinin arızalandığını veya aşırı ısındığını gösterir." },
        { q: "Windows'ta 'Yüksek Performans' modu seçilmeli mi?", a: "Masaüstü bilgisayarlarda işlemcinin sürekli yüksek hızda kalmasını sağlar, tepkiselliği artırabilir." },
        { q: "Sanal Makine (VM) performansı etkiler mi?", a: "Açık olduğu sürece RAM ve CPU'nun büyük bir kısmını rezerve ettiği için oyun performansını düşürür." },
        { q: "Anti-Cheat yazılımları bilgisayarı yavaşlatır mı?", a: "Bazı agresif anti-cheat sistemleri (Kernel level) arka planda kaynak tüketerek performansı bir miktar etkileyebilir." },
        { q: "TDP (Thermal Design Power) nedir?", a: "Bir bileşenin yaydığı ve soğutma sisteminin uzaklaştırması gereken maksimum ısı miktarıdır (Watt cinsinden)." },
        { q: "Coil Whine yazılımla geçer mi?", a: "FPS'i sabitlemek (Örn: 144 FPS) bobinlere binen yükü azaltarak cızırtı sesini azaltabilir veya tamamen kesebilir." },
        { q: "Oyunlarda 'Ultra' ayar her zaman gerekli mi?", a: "Çoğu oyunda 'High' ve 'Ultra' arasındaki görsel fark çok azdır ancak performans yükü Ultra'da çok daha fazladır." },
        { q: "Anlık takılmalar (Frame Drop) için ilk kontrol ne olmalıdır?", a: "Sıcaklık değerleri (MSI Afterburner ile) ve arka plandaki disk kullanımı kontrol edilmelidir." },
        { q: "SSD'de boş alan bırakmak performansı etkiler mi?", a: "Evet, SSD'lerin yazma hızı ve ömrü için en az %15-20 boş alan bırakmak kritiktir." },
        { q: "Windows 10 desteği ne zaman bitiyor?", a: "Ekim 2025'te resmi destek sona erecek; o zamana kadar Windows 11'e geçmek güvenlik için önemlidir." },
        { q: "Mera AI bana her konuda yardımcı olabilir mi?", a: "Kesinlikle! Donanım, yazılım veya sistem toplama hakkında aklına takılan her şeyi buradaki dev kütüphanemle cevaplayabilirim." }
    ]
};

// --- KÜTÜPHANE MOTORU (GÜNCEL VE HİBRİT UYUMLU) ---

export function renderLibrary(filter = "") {
    const listContainer = document.getElementById('lib-list');
    if (!listContainer) return;

    // İçeriği temizle
    listContainer.innerHTML = "";
    const searchTerm = filter.toLowerCase().trim();

    for (const category in KNOWLEDGE_BASE) {
        // Arama filtresi: Hem soruda hem cevapta ara (Kullanıcı cevabı görmese de aratabilir)
        const categoryItems = KNOWLEDGE_BASE[category].filter(item => 
            item.q.toLowerCase().includes(searchTerm) || 
            item.a.toLowerCase().includes(searchTerm)
        );

        if (categoryItems.length > 0) {
            // Kategori Başlığı (style.css'deki .lib-cat sınıfı ile uyumlu)
            const categoryHeader = document.createElement('div');
            categoryHeader.className = 'lib-cat'; 
            categoryHeader.innerHTML = `<h4>${category}</h4>`;
            listContainer.appendChild(categoryHeader);

            categoryItems.forEach(item => {
                const itemDiv = document.createElement('div');
                itemDiv.className = 'lib-item'; // Sadece soru görünecek yapı
                
                // Sadece soruyu yazıyoruz, ok ikonu CSS ile otomatik gelecek
                itemDiv.innerHTML = `<strong>${item.q}</strong>`;
                
                // TIKLAMA OLAYI: Soruyu ana sohbet ekranına (Mera AI'ya) gönderir
                itemDiv.addEventListener('click', () => {
                    if (window.autoMsg) {
                        window.autoMsg(item.q); // Soruyu otomatik yaz ve gönder
                        window.toggleLib(); // Seçim yapınca kütüphane panelini kapat
                    }
                });
                
                listContainer.appendChild(itemDiv);
            });
        }
    }

    // Sonuç bulunamadıysa uyarı göster
    if (listContainer.innerHTML === "") {
        const noResult = document.createElement('p');
        noResult.style.cssText = "padding:20px; color:#999; font-size:13px; text-align:center;";
        noResult.innerText = "Aradığınız kriterde bir soru bulunamadı...";
        listContainer.appendChild(noResult);
    }
}